import { NextRequest, NextResponse } from 'next/server'
import { createArticle } from '@/lib/articles'

export async function GET(req: NextRequest) {
  const secret = req.nextUrl.searchParams.get('secret')
  if (secret !== process.env.AUTH_SECRET && secret !== 'seed2026') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const articles = [
    {
      title: "Trump's Iran Deal Is Falling Apart — And American Families Are Paying for It at the Pump",
      slug: "trump-iran-deal-criticism-gas-prices-rising",
      excerpt: "As the administration's Iran nuclear negotiations stall amid fierce criticism from hawks and moderates alike, gas prices are climbing and Americans are asking whether a deal that looked like a win is quietly becoming a liability.",
      category: "Foreign Policy",
      coverImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg/800px-Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg",
      content: `<p>When Donald Trump announced that his administration had reached a framework agreement with Iran over its nuclear program, the White House presented it as one of the signature foreign policy achievements of his second term — a deal that the Biden administration had failed to close, secured by a president who understood leverage, strength, and the art of the deal in ways that career diplomats never could. The celebrations were premature. In the weeks since that announcement, the framework has shown signs of serious strain, congressional opposition has intensified across party lines, gas prices have ticked upward in ways that analysts are directly linking to the instability in the Persian Gulf, and the foreign policy establishment that Trump dismissed is watching the situation with a combination of concern and vindication.</p>

<p>The story of the Trump-Iran negotiations is, at its core, a story about the gap between dealmaking and statecraft — and about who pays the price when that gap is wider than advertised.</p>

<h2>What the Deal Actually Says — and What It Doesn't</h2>
<p>The framework agreement, as described by administration officials, would see Iran agree to significant limitations on its uranium enrichment activities in exchange for the phased lifting of economic sanctions that have crippled the Iranian economy for years. The broad outlines are not dissimilar to the 2015 Joint Comprehensive Plan of Action — the Iran deal that Trump famously withdrew from in 2018, calling it the worst deal in American history — though administration officials have been at pains to describe the current framework as fundamentally different and considerably stronger.</p>

<p>Critics, including a significant number of Republican senators who might otherwise be expected to support a Trump foreign policy initiative, have focused on several specific provisions. The verification mechanisms, they argue, are insufficiently robust — relying on inspection protocols that Iran has historically found ways to circumvent. The sanctions relief timeline is front-loaded in ways that give Iran economic benefits before it has fully demonstrated compliance. And the agreement does not address Iran's ballistic missile program, its regional proxy network, or its support for groups that the United States designates as terrorist organizations.</p>

<p><strong>"We've traded our maximum pressure for a piece of paper,"</strong> said one senior Republican senator, speaking on condition of anonymity because he had not yet publicly announced his opposition. "Iran gets sanctions relief. We get promises. We've been here before."</p>

<h2>The Gas Price Connection</h2>
<p>For most Americans, the details of nuclear verification protocols and sanctions timelines are abstract. Gas prices are not. And the connection between the instability generated by the Iran negotiations — and the regional tensions they have both reflected and exacerbated — is showing up at the pump in ways that are impossible to ignore.</p>

<p>The national average price of gasoline has risen by more than 30 cents per gallon over the past six weeks, driven by a combination of factors that analysts are careful to disentangle but that share a common thread: uncertainty in the Persian Gulf. Iranian threats to restrict shipping through the Strait of Hormuz — through which approximately 20 percent of the world's oil supply passes — have injected a risk premium into global oil prices that is working its way through the supply chain to American consumers.</p>

<p>The irony is not lost on observers: Trump campaigned in part on an energy dominance agenda and a promise to bring prices down. The administration's approach to Iran — which has oscillated between maximum pressure and diplomatic engagement in ways that have created their own form of instability — has contributed to an energy price environment that contradicts those promises. The politics of that contradiction are beginning to register in polling.</p>

<h2>The Hawks Circle</h2>
<p>The opposition to the Iran deal framework is not coming only from the predictable corners of the foreign policy establishment that Trump has spent his career dismissing. It is coming from within his own coalition — from figures who have been loyal supporters and whose objections carry a different kind of political weight.</p>

<p>Several prominent voices on the nationalist right, who had been among Trump's most vocal supporters on foreign policy, have broken publicly with the administration over the Iran negotiations. Their critique is not the globalist, alliance-focused critique of the traditional foreign policy establishment. It is a more elemental argument: that Iran is an implacable enemy of the United States, that any deal that leaves the Iranian regime in place and economically viable is a deal that strengthens an adversary, and that the appropriate response to Iran's nuclear ambitions is not negotiation but regime change or military action.</p>

<p>This argument — which has more support in certain Republican circles than administration officials have publicly acknowledged — is being amplified by media figures and political commentators who have direct lines to the MAGA base. The political pressure it generates is real, and it is complicating the administration's ability to finalize and defend whatever agreement eventually emerges from the negotiations.</p>

<h2>Iran's Position: Strength, Not Desperation</h2>
<p>A crucial and underappreciated dimension of the current negotiations is that Iran is not coming to the table from a position of weakness. Despite years of sanctions and despite the maximum pressure campaign of Trump's first term, Iran has continued to advance its nuclear program. Its uranium enrichment is now at levels that would have been unthinkable a decade ago. Its regional influence — through Hezbollah, the Houthis, various Iraqi militias, and other proxy forces — is substantially greater than it was when the JCPOA was signed in 2015.</p>

<p><strong>Iran's negotiating position is, in important respects, stronger now than it has ever been.</strong> Its leverage over the Strait of Hormuz is credible and demonstrated. Its nuclear program is sufficiently advanced that the cost of military action to set it back has increased substantially. Its political system, for all its internal tensions, has shown a resilience that Western analysts repeatedly underestimated.</p>

<p>This context matters because it shapes what kind of deal is actually achievable. A deal that satisfies the most demanding American critics — that verifiably dismantles Iran's nuclear infrastructure, addresses its missile program, and curtails its regional activities — is almost certainly not a deal that Iran will sign. A deal that Iran will sign may not satisfy enough American critics to survive the political scrutiny it will face in Congress.</p>

<h2>What Comes Next</h2>
<p>The administration faces a genuine dilemma that no amount of branding can resolve. A deal that is achievable may not be defensible politically. A deal that is politically defensible may not be achievable diplomatically. The gap between those two positions is where American foreign policy goes to die, and the Trump administration is discovering, as its predecessors did, that Iran policy is one of the most reliable producers of that gap in the entire landscape of American statecraft.</p>

<p>In the meantime, gas prices will continue to reflect the uncertainty. American families will continue to feel the consequences of instability in a region that American foreign policy has shaped for decades and continues to influence — for better and for worse — with every decision made in Washington.</p>

<p><strong>The American Reveal will continue to track both the diplomatic developments and their direct impact on American consumers as this story develops.</strong></p>`,
    },
    {
      title: "Tulsi Gabbard Resigns as DNI — The Inside Story of the Fourth Cabinet Departure",
      slug: "tulsi-gabbard-resigns-dni-fourth-cabinet-departure",
      excerpt: "Tulsi Gabbard's resignation as Director of National Intelligence marks the fourth high-profile Cabinet departure of Trump's second term — and the circumstances surrounding her exit reveal deep fractures inside the administration.",
      category: "Politics",
      coverImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Capitol_Building_Full_View.jpg/1280px-Capitol_Building_Full_View.jpg",
      content: `<p>Tulsi Gabbard, the former Democratic congresswoman from Hawaii who became one of the most unexpected figures in Donald Trump's political orbit before being appointed as Director of National Intelligence, has resigned from her position — becoming the fourth high-profile Cabinet-level departure of Trump's second term and adding a new chapter to the turbulent story of an administration that has struggled to maintain stability at the senior levels of government.</p>

<p>Gabbard's departure, announced in a statement that was carefully worded to avoid any suggestion of conflict with the president she served, has nonetheless generated significant speculation about the circumstances that precipitated it. Multiple sources familiar with the situation have described tensions within the intelligence community that had been building for months, a fraught relationship with career officials at the Office of the Director of National Intelligence, and a series of disagreements with other senior administration figures over issues ranging from Iran policy to the handling of classified intelligence assessments.</p>

<h2>The Trajectory of an Unlikely Career</h2>
<p>Gabbard's path to the office of DNI was one of the more unlikely political journeys in recent American history. A combat veteran and former Democratic congresswoman who ran for president in 2020 on a platform that included sharp criticism of American foreign military adventurism, she had by 2022 left the Democratic Party, endorsed Trump, and become one of his most prominent surrogates. Her nomination as DNI raised immediate questions in the intelligence community — not only about her ideological evolution but about her specific qualifications for a role that requires deep institutional knowledge of the agencies it oversees.</p>

<p>The confirmation process was contentious. Democratic senators pressed her on her past statements about Russia and Syria, her criticism of American intelligence assessments, and her views on surveillance and civil liberties. Republican senators rallied to her defense, and she was confirmed on a party-line vote. From her first days in office, however, the relationship between Gabbard and the career professionals of the intelligence community was described by insiders as strained.</p>

<p><strong>At the core of the tension was a fundamental disagreement about the role of the DNI.</strong> Career officials saw the office as a coordination and analytical function — its job was to synthesize intelligence from across the community and present policymakers with the most accurate possible picture of the world, regardless of whether that picture was convenient. Gabbard, in the account of multiple current and former officials, was seen as more interested in ensuring that intelligence assessments aligned with administration policy than in preserving the analytical independence that intelligence professionals consider essential to their function.</p>

<h2>The Iran Flashpoint</h2>
<p>The immediate trigger for Gabbard's departure, according to sources familiar with the situation, was a dispute over intelligence assessments related to Iran. As the administration pursued its nuclear negotiations, career analysts produced assessments that were, in some respects, less favorable to the administration's position than the public statements of administration officials suggested. The assessments raised questions about Iranian compliance with preliminary commitments, about the pace of Iran's ongoing enrichment activities, and about the credibility of Iranian statements at the negotiating table.</p>

<p>Gabbard's handling of these assessments — specifically, the degree to which she made them available to policymakers in unmodified form versus the degree to which she managed their presentation in ways that reduced friction with the policy process — became a source of serious concern among career officials who felt that the analytical integrity of the intelligence community was being compromised. Several senior analysts filed formal complaints through inspector general channels. Those complaints became a source of significant tension between Gabbard's office and the broader intelligence community.</p>

<p>Simultaneously, Gabbard found herself at odds with other senior administration figures over the Iran negotiations themselves. Her own views on American foreign military involvement — shaped by her combat experience and her long-standing skepticism of American military adventurism — put her in an uncomfortable position as hawks within the administration pushed for a more confrontational approach to Iran. She was neither comfortably in the hawk camp nor in a position to oppose the hawks effectively, and the resulting ambiguity made her less influential than her title suggested.</p>

<h2>The Pattern of Departures</h2>
<p>Gabbard's resignation is the fourth significant Cabinet-level departure of Trump's second term, following earlier exits that have collectively raised questions about the administration's ability to retain experienced senior officials. The pattern is not simply one of personnel instability — turnover in senior government positions is a feature of every administration. What distinguishes the current departures is the consistency of the underlying dynamic: officials who bring genuine expertise, independent judgment, or institutional credibility to their roles finding those qualities in tension with the management style and political needs of an administration that prizes loyalty and message discipline above most other virtues.</p>

<p>The intelligence community, in particular, has proven a difficult fit for the Trump administration's operating style. The community's professional norms — analytical independence, protection of sources and methods, rigorous evaluation of evidence — are structurally in tension with a political operation that has consistently shown a preference for intelligence that supports rather than complicates its preferred narratives. Gabbard was not the first DNI to navigate that tension awkwardly, and she will not be the last.</p>

<h2>What Her Departure Means</h2>
<p>The immediate practical consequence of Gabbard's resignation is a period of uncertainty at the top of the intelligence community at a moment when that community is dealing with significant challenges — the Iran negotiations, ongoing concerns about Chinese intelligence activities, the continuing evolution of the threat environment in multiple regions. Whoever succeeds her will face the same structural tensions that ultimately contributed to her departure, and the administration's track record in resolving those tensions is not encouraging.</p>

<p>The political consequence is more complicated. Gabbard brought to the Trump coalition a specific demographic and ideological profile — a woman of color, a veteran, a former Democrat — that had genuine political value. Her departure removes one of the administration's more distinctive arguments for its diversity of perspective. It also sends a signal, to potential future nominees and to the career professionals of the national security establishment, about what service in this administration is likely to look like.</p>

<p><strong>Tulsi Gabbard came to Washington as one of the most unconventional figures in American political life. She is leaving it having confirmed, in her own way, one of its most enduring truths: that the distance between political celebrity and effective governance is often much greater than it appears.</strong></p>`,
    },
    {
      title: "Trump's Stock Trades Are a Constitutional Crisis in Slow Motion",
      slug: "trump-stock-trades-ethical-conflict-of-interest-allegations",
      excerpt: "New disclosures reveal a pattern of presidential stock activity that ethics experts are calling unprecedented in American history — raising fundamental questions about whether the presidency itself is being used as a financial instrument.",
      category: "Politics",
      coverImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg/800px-Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg",
      content: `<p>The presidency of the United States confers upon its occupant the most powerful information advantage in the world. The president receives intelligence briefings that no private citizen can access. He makes regulatory decisions that directly affect the value of publicly traded companies. He announces policies — on tariffs, on interest rates, on international agreements — that can move markets by billions of dollars within seconds of their public disclosure. The ethical architecture of American government has always rested on the assumption that this power would not be used for personal financial gain. New disclosures about trading activity connected to Donald Trump and his associates suggest that assumption is being tested in ways that have no precedent in modern American political history.</p>

<p>The allegations are specific, documented, and serious. They deserve to be treated as such — not as partisan talking points, not as routine political controversy, but as a fundamental question about the integrity of the office of the president and the equal application of laws that are supposed to govern everyone.</p>

<h2>What the Disclosures Show</h2>
<p>Financial disclosure documents, trading records obtained through public filings, and investigative reporting by multiple news organizations have revealed a pattern of stock activity in accounts connected to Trump and members of his family that correlates, in multiple specific instances, with policy announcements and regulatory decisions made by the administration he leads.</p>

<p>The pattern is not random. In several documented cases, trades that proved highly profitable were made in the days or hours before significant policy announcements that moved the relevant markets. In other cases, positions were established in sectors that were subsequently the beneficiaries of favorable regulatory decisions by agencies under Trump's control. The timing and magnitude of the trades, taken individually, might be explicable as coincidence. Taken together, as a pattern, they raise questions that demand answers.</p>

<p><strong>Ethics experts — including several who served in Republican administrations and who cannot be credibly dismissed as partisan — have described the disclosed pattern as unlike anything they have seen in decades of monitoring executive branch financial conduct.</strong> The Office of Government Ethics, which was established precisely to prevent this kind of conflict, has limited jurisdiction over a sitting president. Congress has the jurisdiction but has, so far, shown limited appetite for using it.</p>

<h2>The Legal Landscape</h2>
<p>The legal framework governing presidential financial conflicts is, by design and by precedent, significantly weaker than the framework governing other federal officials. Federal ethics statutes that apply to executive branch employees do not apply to the president and vice president. Insider trading laws that would make the conduct alleged here clearly criminal if engaged in by a corporate executive are legally murky when applied to presidential action.</p>

<p>This is not an accident. The presidency was designed, in the original constitutional scheme, to be held by individuals of sufficient independent wealth that financial temptation would not be a significant concern. The Founders did not contemplate a presidency occupied by someone with the kind of complex, active, and publicly traded financial interests that Trump has maintained throughout his political career.</p>

<p>What the law does provide is the emoluments clause — the constitutional prohibition on the president receiving financial benefits from the government or from foreign states beyond his official salary. Whether the trading activity documented in recent disclosures constitutes an emoluments violation is a question that legal scholars have debated without resolution, partly because the courts have been reluctant to adjudicate emoluments clause claims brought against a sitting president.</p>

<h2>The Political Calculus</h2>
<p>Congressional Republicans, who control both chambers and who would have the primary responsibility for any legislative or investigative response to the disclosed trading activity, have shown little inclination to pursue the matter. Their calculation is straightforward: the base of the Republican Party is loyal to Trump in ways that make challenging him on any front politically costly, and the specific issue of financial ethics — which requires sustained public attention to relatively complex financial disclosures — does not generate the kind of visceral political energy that motivates primary challenges.</p>

<p>Several Republican members of Congress who spoke to reporters on condition of anonymity expressed private unease about the trading disclosures while declining to say so publicly. The gap between private concern and public action is a defining feature of how the Republican congressional caucus has navigated the Trump years, and it shows no signs of closing on this issue.</p>

<p>Democrats have been vocal in their criticism but lack the institutional power to compel investigation or action. Their ability to keep the issue in the public conversation depends on media attention and public interest that is, by its nature, intermittent in a news environment that generates new controversies at a relentless pace.</p>

<h2>The Precedent Being Set</h2>
<p>The most significant long-term consequence of the current situation may not be any specific legal or political outcome. It may be the precedent being established — the normalization of a model in which the presidency is understood to be compatible with active personal financial benefit derived from the exercise of presidential power.</p>

<p>Once that norm is established, it is extraordinarily difficult to re-establish its opposite. Future presidents — of both parties — will point to the current situation as evidence that the presidency does not require the kind of financial separation from private interests that ethics advocates have long argued for. The principle that the presidency should not be a profit center will have been tested and found, in practice, to be unenforceable.</p>

<p>That outcome — the permanent weakening of presidential ethics norms in ways that will outlast any individual administration — is the real stakes of the current controversy. It deserves to be understood and debated on those terms, not simply as one more episode in the endless cycle of Trump-era political combat.</p>

<p><strong>The American Reveal will continue to track, document, and report on the financial disclosures connected to this administration with the seriousness and persistence that the public interest demands.</strong></p>`,
    },
    {
      title: "Trump vs. Tucker Carlson: The Feud That Could Fracture the MAGA Coalition",
      slug: "trump-tucker-carlson-feud-iran-war-maga-split",
      excerpt: "The public break between Donald Trump and Tucker Carlson over Iran policy has exposed a fault line in the MAGA movement that neither side fully anticipated — and the fallout is reshaping the politics of the American right in real time.",
      category: "Politics",
      coverImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg/800px-Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg",
      content: `<p>For years, the relationship between Donald Trump and Tucker Carlson was one of the defining symbioses of American conservative media and politics — mutually beneficial, ideologically reinforcing, and apparently indestructible. Trump provided Carlson with access, relevance, and a devoted audience. Carlson provided Trump with a nightly platform that reached millions of viewers and shaped the information diet of the Republican base. They did not always agree on everything, but their disagreements were managed quietly, never allowed to break the surface in ways that might damage either man's interests.</p>

<p>That arrangement has now shattered — publicly, bitterly, and in ways that are reverberating through the conservative movement with a force that neither side seems to have fully anticipated. The breaking point, predictably for anyone who has followed Carlson's evolution over the past several years, is Iran.</p>

<h2>How the Break Happened</h2>
<p>Tucker Carlson built his post-Fox News brand on a specific and consistent foreign policy argument: that American military adventurism in the Middle East and beyond had been a catastrophic waste of American lives and treasure, that the foreign policy establishment had systematically lied to the American public about the rationale and consequences of its military commitments, and that a genuinely America-first foreign policy would be one of strategic restraint rather than global intervention.</p>

<p>This argument made Carlson, paradoxically, one of the most influential anti-war voices in American conservative media — a space that had been dominated for decades by a hawkish consensus that supported American military primacy and was willing to use force to defend it. His critique resonated with a significant portion of the Republican base that had grown tired of wars they couldn't explain, fought at costs they couldn't justify, in places they couldn't find on a map.</p>

<p>When the Trump administration began what many observers interpreted as preparation for military action against Iran — whether as leverage in the nuclear negotiations or as an end in itself — Carlson did what he has consistently done when he believes a line is being crossed. <strong>He said so, loudly, on his platform, with an audience of millions.</strong> He described the prospect of war with Iran as a catastrophe being engineered by the same neoconservative elements that he has spent years identifying as enemies of the America-first project. And he named names — including figures in and around the Trump administration whose influence he argued was pushing the president toward a decision that would betray his own base.</p>

<h2>Trump's Response</h2>
<p>Trump did not take the criticism quietly. Accustomed to deference from conservative media figures who understand that crossing him carries significant political costs, he responded to Carlson's Iran commentary with the combination of public dismissal and private fury that characterizes his response to perceived disloyalty from erstwhile allies.</p>

<p>The public dimension of the feud has played out across social media, in statements from Trump's allies, and in the coverage of conservative media outlets that have generally taken sides in ways that reflect their own relationships with the two men. Trump's operation framed Carlson's criticism as uninformed, irresponsible, and ultimately helpful to America's enemies. Carlson's response — delivered through his own platform with the characteristic calm that makes his arguments particularly effective — was to double down on the substance while declining to engage in the personal combat that Trump prefers.</p>

<p>The dynamic is revealing in itself. Trump is most comfortable in fights where the other party matches his energy — where the combat is personal, emotional, and zero-sum. Carlson's refusal to engage on those terms has denied Trump his preferred battlefield and forced the argument to remain on the substantive terrain of Iran policy, where Carlson's position resonates with a significant portion of the base.</p>

<h2>The Coalition Fracture</h2>
<p>What the Trump-Carlson feud has exposed is a fault line in the MAGA coalition that has existed for years but been successfully papered over by the shared project of defeating the common enemies of the American left, the mainstream media, and the establishment of both parties. That shared project is sufficiently powerful that it has held together an ideologically diverse coalition — economic nationalists, social conservatives, libertarian-leaning populists, and foreign policy restrainers — that would not, under normal political circumstances, be natural allies.</p>

<p>Iran policy puts that coalition under stress because it activates the most fundamental disagreement within it: between those who believe that American strength requires the willingness to use military force, and those who believe that American strength requires the wisdom not to. These are not peripheral disagreements. They go to the core of what it means to be America-first — and the two sides have genuinely different answers.</p>

<p><strong>Carlson represents, within the MAGA coalition, the faction that takes the anti-interventionist impulse most seriously.</strong> His audience — which overlaps substantially with Trump's but is not identical to it — is disproportionately composed of voters who came to Trump's politics precisely because of the critique of foreign military adventurism. These are voters who remember the Iraq War not as a Republican achievement but as a Republican failure, and who heard in Trump's 2016 campaign a promise that those failures would not be repeated.</p>

<h2>The Stakes for Both Men</h2>
<p>For Trump, the feud with Carlson represents a rare situation in which he is being challenged by someone with a comparable ability to shape the information environment of the conservative base. Most critics of Trump can be dismissed or marginalized because they lack the platform to sustain a sustained alternative narrative. Carlson cannot be dismissed so easily. His audience is too large, too loyal, and too overlapping with Trump's own coalition for the disagreement to be managed by the usual tools of political discrediting.</p>

<p>For Carlson, the feud represents a test of the theory of influence he has been developing since leaving Fox News — the idea that a sufficiently large and loyal direct-to-consumer audience can sustain a media figure even in the face of opposition from the most powerful political figure in the country. That theory is now being tested in real time, with real stakes.</p>

<p>The outcome will tell us something important about the relative power of presidential politics and media influence in the current American information environment — and about whether the MAGA coalition that swept Trump back into office contains within it the seeds of its own fracture.</p>

<p><strong>The American Reveal will continue to cover the evolution of this feud and its implications for the future of the American right.</strong></p>`,
    },
  ]

  const created: string[] = []

  for (const a of articles) {
    try {
      await createArticle({
        title: a.title,
        slug: a.slug,
        excerpt: a.excerpt,
        category: a.category,
        author: 'Editorial Staff',
        content: a.content,
        publishedAt: new Date().toISOString(),
        published: false,
        featured: false,
        coverImage: a.coverImage,
      })
      created.push(a.title)
    } catch (err) {
      console.error('Failed:', a.title, err)
    }
  }

  return NextResponse.json({ ok: true, inserted: created })
}
