#!/usr/bin/env python3
"""Build expanded articles.json - Part 2 (articles 8-16)"""
import json

with open('data/articles_partial.json', 'r') as f:
    articles = json.load(f)

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 8: new-article-003 — Trump's Shifting Story on Epstein
# ─────────────────────────────────────────────────────────────────────────────
a8_figure = '<figure><img src="https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80" alt="Donald Trump official portrait" /><figcaption>Donald Trump — official portrait. His public statements about his relationship with Jeffrey Epstein changed dramatically between 2002 and 2024, as the political exposure of that relationship grew. Credit: The White House / Public Domain</figcaption></figure>'

a8_body = """
<h2>2002: The Quote That Cannot Be Walked Back</h2>
<p>In October 2002, New York Magazine published a profile of Jeffrey Epstein by journalist Landon Thomas Jr. Donald Trump, then a prominent New York businessman and television personality, offered the following quote — voluntarily, without any obligation to participate in a story that was not primarily about him: <em>"I've known Jeff for fifteen years. Terrific guy. He's a lot of fun to be with. It is even said that he likes beautiful women as much as I do, and many of them are on the younger side. No doubt about it — Jeffrey enjoys his social life."</em></p>
<p>The quote establishes three things with the specificity that only an unguarded, voluntary statement can: a long-standing personal acquaintance of at least fifteen years as of 2002, genuine personal warmth toward the subject, and — in retrospect — what reads either as a knowing acknowledgment of or an unconscious allusion to precisely the behavior for which Epstein would be prosecuted. The phrase "many of them are on the younger side," offered as an admiring observation, is not a warning. It is a compliment.</p>
<p>This quote is the foundation of any honest accounting of the Trump-Epstein relationship, not because it proves anything beyond its literal content, but because it was not crafted defensively. Trump spoke as a man describing a friend to a journalist writing a favorable profile. It represents the most credible statement he has ever made about Jeffrey Epstein — precisely because he had no reason at the time to manage its political implications.</p>
<h2>The Timeline of Revisions</h2>
<p>What follows is a documented chronology of how Trump's public characterizations of his relationship with Epstein changed over the two decades that followed that 2002 statement:</p>
<p><strong>2002:</strong> "I've known Jeff for fifteen years. Terrific guy. He's a lot of fun to be with." (New York Magazine)</p>
<p><strong>2003-2014:</strong> Trump made no public statements about Epstein during this period that have been recovered in contemporaneous reporting. Their social overlap continued to be documented in photographs and event records.</p>
<p><strong>2015:</strong> As Trump launched his presidential campaign and scrutiny of his associations intensified, he told reporters: "I knew him like everybody in Palm Beach knew him. He was a fixture in Palm Beach. I had a falling-out with him. I haven't spoken to him in many years." The friend he had known "for fifteen years" was now recharacterized as a social fixture whom Trump knew the way everyone knew him — a formulation that converted a named personal friendship into an impersonal ambient social acquaintance.</p>
<p><strong>July 2019</strong> (following Epstein's federal arrest in New York): "I knew him. He was a fixture in Palm Beach. I had a falling-out with him a long time ago. I don't think I've spoken to him for 15 years. I was not a fan of his, that I can tell you."</p>
<p><strong>August 2019</strong> (following Epstein's death in custody): "I was not a fan of Jeffrey Epstein."</p>
<p><strong>July 2020</strong> (following Ghislaine Maxwell's arrest): When asked about Maxwell — who attended his 2005 wedding — Trump said: "I wish her well, frankly. I've met her numerous times over the years, especially since I lived in Palm Beach, and I guess they lived in Palm Beach. But I wish her well, whatever it is." The spontaneous warmth of this response, directed at a woman who would be convicted of sex trafficking a minor, was widely noted as inconsistent with his claims of having distanced himself from the Epstein world years earlier.</p>
<p><strong>2024:</strong> Campaign and White House statements have described Trump's relationship with Epstein as minimal — a businessman's casual encounter with a Palm Beach figure — and have emphasized the unverified claim that Trump banned Epstein from Mar-a-Lago following a complaint from a club member.</p>

<figure><img src="https://images.unsplash.com/photo-1577083165350-14c11b1f6db5?auto=format&fit=crop&w=800&q=80" alt="Jeffrey Epstein Palm Beach mug shot" /><figcaption>Jeffrey Epstein, whose social relationship with Trump was documented in flight logs, photographs, and Trump's own 2002 public statements. Trump's description of that relationship has contracted significantly over time. Credit: Palm Beach County Sheriff's Office / Public Domain</figcaption></figure>

<h2>The Flight Log Evidence</h2>
<p>The shifting characterization stands in direct tension with the documentary record. Flight logs obtained through civil litigation show that Trump traveled on Epstein's Boeing 727 on at least one documented occasion in the early 1990s — a flight from Palm Beach to New York recorded in logs that were subpoenaed as part of civil proceedings by Epstein's victims and subsequently reported by Fox News and The Daily Beast. The logs were first reported comprehensively by journalist Nick Bryant.</p>
<p>Trump's representatives have disputed the characterization of this flight, arguing that it was a chartered flight on which both Trump and Epstein happened to be passengers. That distinction, to the extent it is accurate, does not explain the 2002 quote, the documented shared social attendance across multiple venues and years, or Trump's own description of knowing Epstein "for fifteen years."</p>
<h2>The Mar-a-Lago Ban Claim: A Story That Changes</h2>
<p>Trump and his allies have repeatedly cited the claim that he banned Epstein from Mar-a-Lago as evidence of Trump's early recognition of Epstein's wrongdoing. The specific account has varied across tellings. In some versions, Trump learned that Epstein had acted inappropriately toward a young woman at the club and immediately expelled him. In others, the expulsion happened in the early 2000s. In others still, the timing is left vague.</p>
<p>No documentary evidence supporting the ban story has been made public. A Mar-a-Lago employee told The Daily Beast in 2019 that she had observed Epstein and Maxwell recruiting at the club, and specifically described Maxwell approaching a 14-year-old girl at a 1996 Mar-a-Lago event. The employee's account is at minimum inconsistent with an early, decisive expulsion — it implies that Epstein and Maxwell's activity at the club continued well into the period when Trump's own account suggests awareness of inappropriate conduct.</p>
<h2>The Lawsuit Trump Fought to Prevent</h2>
<p>In April 2016, a woman identifying herself as Jane Doe filed a federal lawsuit in California alleging that she had been trafficked to Trump by Epstein as a 13-year-old in 1994. The complaint was refiled in June 2016 in the Southern District of New York with a sworn declaration from the plaintiff and a corroborating sworn declaration from a witness. Trump's legal team moved aggressively to dismiss the complaint and to challenge the identity of the plaintiff, who was represented by attorney Cheney Mason and subsequently by other attorneys.</p>
<p>The case was voluntarily dismissed in November 2016, days before the presidential election. The plaintiff's then-attorney stated publicly that she had received death threats and could not safely proceed. No court ruled on the merits. Trump has denied all of the allegations in the complaint with particular intensity. The case has never been adjudicated on its facts.</p>
<p>What is documentable is that Trump's legal team treated the case as a significant threat and fought its continuation strenuously. The question of what a deposition of Trump, under oath, about his relationship with Epstein and the specific factual allegations of the complaint would have revealed remains unanswered.</p>
<h2>The Pattern</h2>
<p>The evolution of Trump's public statements about Epstein follows a recognizable pattern: voluntary affirmation of the relationship when it carried no political risk; gradual recharacterization as political scrutiny grew; eventual repudiation as the legal and political stakes became clear. The 2002 quote remains the clearest window into what Trump understood the relationship to be. Everything that followed represents the management of that understanding's political implications — not its repudiation.</p>
<div class="sources"><strong>Sources:</strong> New York Magazine, Landon Thomas Jr., "Jeffrey Epstein: International Moneyman of Mystery" (October 2002); Trump statements to The Hill and other outlets (July 2019); Trump statement on Maxwell (July 2020); The Daily Beast reporting on Mar-a-Lago and Epstein (2019); flight log records in civil litigation, reported by Fox News and The Daily Beast; civil complaint, Jane Doe v. Trump and Epstein, SDNY (2016); Trump campaign statements (2024); reporting by ProPublica and New York Magazine.</div>"""

a8_content = a8_figure + a8_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 9: new-article-004 — Trump Before and After the Presidency
# ─────────────────────────────────────────────────────────────────────────────
a9_figure = '<figure><img src="https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80" alt="Donald Trump official portrait" /><figcaption>Donald Trump — 47th President of the United States. His two terms in office have been defined, in part, by the gap between campaign rhetoric promising accountability and a governing record that critics argue reinforced the very systems he promised to dismantle. Credit: The White House / Public Domain</figcaption></figure>'

a9_body = """
<h2>The Candidate and the Institution</h2>
<p>On June 16, 2015, Donald Trump descended a golden escalator in Trump Tower and declared his candidacy for the presidency with a speech that positioned him as a radical outsider to the corrupt political establishment. He would drain the swamp. He would lock up his political opponents. He would put America first. He was the only candidate with the personal resources and independence to take on the interests that had captured both parties.</p>
<p>The crowds that responded to this message did so with genuine conviction. Many of Trump's 2016 supporters were people who had watched the political system fail them — through deindustrialization, the 2008 financial crisis, a healthcare system that excluded them, a justice system they correctly perceived as operating differently for the powerful. Trump's outsider message was compelling precisely because it named a real problem. The question is what happened to those promises when they met the actual mechanics of governance — and what the record of two administrations reveals about the gap between campaign rhetoric and governing reality.</p>
<h2>Drain the Swamp: The Promise and the Record</h2>
<p>The "drain the swamp" rhetoric carried specific implications: fewer lobbyists in government, stronger ethics rules, an end to the revolving door between industry and the regulatory agencies that were supposed to oversee it. What the Trump administration delivered, according to analysis by nonpartisan watchdog organizations including Public Citizen, the Government Accountability Project, and the Revolving Door Project, was a record number of lobbyists and industry insiders appointed to federal positions — many to agencies specifically responsible for regulating their former employers.</p>
<ul>
<li>More than 180 former lobbyists were appointed to federal positions in Trump's first administration, according to a 2020 analysis by The New York Times and ProPublica — more than any administration in recent history had appointed in a comparable period</li>
<li>The Environmental Protection Agency was placed successively under Scott Pruitt, who had sued the EPA multiple times on behalf of energy industry clients as Oklahoma attorney general, and then Andrew Wheeler, a former coal industry lobbyist</li>
<li>The Department of Labor was led by Alexander Acosta — the former U.S. Attorney who had negotiated Jeffrey Epstein's 2008 non-prosecution agreement — until public pressure following the Miami Herald's reporting forced his resignation in July 2019</li>
<li>The Interior Department's Ryan Zinke resigned under multiple federal ethics investigations. His successor, David Bernhardt, was a former oil and gas industry lobbyist who recused himself from dozens of regulatory decisions involving his former clients but remained involved in shaping the agency's overall direction</li>
</ul>

<figure><img src="https://images.unsplash.com/photo-1523995462485-3d171b5c8fa9?auto=format&fit=crop&w=800&q=80" alt="The White House" /><figcaption>The White House — where two Trump administrations pursued tax policies, regulatory rollbacks, and pardon decisions that critics argued served elite interests at the expense of the accountability rhetoric that powered his campaigns. Credit: Wikimedia Commons</figcaption></figure>

<h2>The Tax Legislation: Who It Actually Helped</h2>
<p>The Tax Cuts and Jobs Act of 2017, the signature legislative achievement of Trump's first term, was presented as relief for working Americans. The Congressional Budget Office, the Tax Policy Center, and multiple independent economists analyzed the legislation's distributional effects with consistency: the law delivered its largest benefits in both percentage terms and absolute dollar amounts to corporations and high-income households.</p>
<p>The corporate tax rate was cut from 35% to 21% — a permanent change. Tax reductions for individual income were mostly structured to expire after 2025. According to the Tax Policy Center's analysis, a family earning $50,000 per year received an average cut of approximately $500. A household earning $500,000 received approximately $16,000. The wealthiest 0.1% of households received an average benefit exceeding $60,000 per year. These are not partisan estimates; they are the products of distributional analysis applied to the actual legislation.</p>
<p>The corporate repatriation provision — intended to bring offshore corporate cash back to America for domestic investment — generated stock buybacks at a record rate rather than the wage growth and capital investment that the bill's proponents had projected. The Federal Reserve Bank of New York documented in published research that the majority of repatriated funds went to shareholders rather than workers.</p>
<h2>Selective Accountability: The Pardons</h2>
<p>"Lock her up" — the rally chant directed at Hillary Clinton — implied a presidency committed to accountability for powerful political figures. What followed was a pattern of accountability that was strikingly and specifically selective. Trump issued presidential pardons to Paul Manafort, his former campaign chairman, convicted of fraud and conspiracy; Roger Stone, convicted of obstruction and witness tampering; Michael Flynn, who had pleaded guilty to lying to the FBI; and Steve Bannon, indicted for fraud in a private border wall fundraising scheme. These pardons were extended to men whose legal jeopardy arose from their service to Trump or their proximity to his network — not to the ordinary citizens whose cases Trump's anti-establishment rhetoric had ostensibly been directed toward.</p>
<p>Hillary Clinton was never charged with any crime. None of the "deep state" officials Trump repeatedly accused of criminality were prosecuted. The "lock her up" chant, as a governing agenda, produced no indictments and no convictions of any of the individuals it was directed at. It produced pardons for Trump's own allies.</p>
<h2>The Epstein Question Under Trump's Watch</h2>
<p>Perhaps nowhere is the gap between promise and record more acute than in the handling of the Epstein case. The populist rhetoric of accountability for the powerful — of equal justice — ran directly into the reality of Epstein's death in federal custody, under a Justice Department whose leader had personally intervened to declare, prematurely, that no foul play was involved. The cameras outside Epstein's cell failed simultaneously. The guards who falsified their logs were charged and then had those charges dropped. No one has been held accountable for what the DOJ's own Inspector General described as a cascade of institutional failures. The man who promised to drain the swamp presided over the most consequential unexplained in-custody death in recent American federal history — and the institutions of accountability functioned exactly as they always have for cases involving the powerful.</p>
<h2>What Two Terms Establish</h2>
<p>The record of two Trump administrations does not establish that Trump's campaign promises were cynical from the outset. It establishes that the structural forces that produce the outcomes he campaigned against — the revolving door, the two-tier justice system, the tax code tilted toward wealth — were not dismantled by his presidency. In some respects, they were reinforced by it. The question that history will ask is not whether Trump meant what he said in 2015. The question is why the system he promised to change remained, after eight years of his influence over it, substantially intact — and who benefited from that outcome.</p>
<div class="sources"><strong>Sources:</strong> Public Citizen and Revolving Door Project analysis of Trump administration appointments (2020); Congressional Budget Office and Tax Policy Center distributional analysis of TCJA (2017-2018); Federal Reserve Bank of New York working paper on repatriation and stock buybacks; reporting by The New York Times and ProPublica on cabinet appointments and conflicts; Department of Justice Inspector General report on Epstein death (2021); Trump pardon records; Miami Herald coverage of Acosta resignation (July 2019).</div>"""

a9_content = a9_figure + a9_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 10: new-article-005 — Court Record: Sexual Abuse Allegations Against Trump
# ─────────────────────────────────────────────────────────────────────────────
a10_figure = '<figure><img src="https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=800&q=80" alt="United States Capitol" /><figcaption>The civil legal system has been the primary venue for adjudicating sexual misconduct allegations against Donald Trump. Two federal jury verdicts in 2023 and 2024 found him liable for sexual abuse and defamation. Credit: Wikimedia Commons</figcaption></figure>'

a10_body = """
<h2>A Legal Record That Demands Examination</h2>
<p>This article reports on formal legal allegations made against Donald Trump in federal and state courts. Everything described below is drawn exclusively from court filings, sworn declarations, jury verdicts, and statements made on the legal record. Where allegations have not been proven in court, they are identified as allegations. Where courts have rendered verdicts, those verdicts are reported as established legal findings. Trump has denied all the allegations described in this article. His denials are on the public record. The existence of denials does not diminish the obligation of journalism to report the full legal record — including what juries have found.</p>
<h2>The E. Jean Carroll Verdicts: What a Jury Found</h2>
<p>E. Jean Carroll is a writer and advice columnist who alleged in published accounts that Donald Trump had sexually assaulted her in the dressing room of the Bergdorf Goodman department store on Fifth Avenue in New York City in the mid-1990s. Trump denied the assault publicly and repeatedly, denied knowing Carroll, and described her account as a fabrication. His denials — made publicly after his presidency ended, and thus not protected by presidential immunity — formed the basis of Carroll's defamation lawsuit.</p>
<p>In May 2023, following a nine-day trial in the Southern District of New York, a federal jury found Donald Trump <strong>liable for sexual abuse and defamation</strong> and awarded Carroll $5 million in damages. The jury's verdict was unambiguous: they found Carroll's account credible, Trump's denials false, and his public statements about her defamatory. The jury did not find rape under the narrow New York legal definition that requires vaginal penetration; it found "sexual abuse," which under New York law encompasses the forcible touching of intimate parts.</p>
<p>In January 2024, a second federal jury, in a separate defamation trial, awarded Carroll an additional $83.3 million after finding that Trump's continued post-trial public denials constituted ongoing defamation. Trump's attorneys immediately moved to reduce the damages; the central finding of liability was not disturbed.</p>
<p>These are not allegations. They are the findings of American citizens who heard evidence presented by both sides under the adversarial process, evaluated witness credibility, and reached conclusions under the civil standard of preponderance of the evidence. Two separate juries, in two separate proceedings, found Trump liable for sexual abuse and defamation in connection with the same underlying events.</p>

<figure><img src="https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80" alt="Donald Trump official portrait" /><figcaption>Donald Trump, found liable for sexual abuse and defamation in two separate federal jury verdicts in 2023 and 2024 in cases brought by writer E. Jean Carroll. Trump has appealed both verdicts. Credit: The White House / Public Domain</figcaption></figure>

<h2>The 2016 Federal Complaint: Jane Doe</h2>
<p>In April 2016, a lawsuit was filed in federal court by a plaintiff identified as Jane Doe, alleging that she had been trafficked by Jeffrey Epstein to Trump as a 13-year-old girl in 1994. The complaint alleged that she was recruited at Epstein's Manhattan residence with promises of modeling work, and that she was subjected to repeated unwanted sexual contact by Trump at parties at that residence over a period of several weeks. The complaint further alleged she was threatened and intimidated into silence.</p>
<p>The case was refiled in June 2016 in the Southern District of New York by attorney Cheney Mason, accompanied by a sworn declaration from the plaintiff and a sworn corroborating declaration from a witness identified as "Tiffany Doe," who described herself as a former Epstein employee who had recruited young women to his residence. In November 2016, days before the presidential election, the plaintiff voluntarily dismissed the case. Her then-attorney stated publicly that she had received death threats and was afraid to continue. No court ruled on the merits of the 2016 complaint. The factual allegations in the complaint were never tested in any evidentiary proceeding.</p>
<p>Trump's legal team denied all allegations and characterized the complaint as politically motivated. Those denials are on the record.</p>
<h2>The Pattern: Twenty-Six Accusers</h2>
<p>Carroll is the only accuser whose claims have been adjudicated by a jury. She is not the only woman to have made public accusations of sexual misconduct against Trump. As of the most recent comprehensive published accounts in 2023, at least 26 women have made public accusations. The accounts vary in their specifics — ranging from groping and unwanted kissing to rape — but share recurring structural features that have been noted by researchers who study patterns of sexual misconduct allegations.</p>
<p>The recurring features include: incidents concentrated in professional or social settings where Trump held power or prestige (the modeling world, beauty pageants, his professional office environment, social events); allegations of sudden, non-consensual physical contact without warning; subsequent pressure through NDAs, legal threats, or social and professional retaliation; and a social context — the world of New York business, celebrity, and elite entertainment that Trump inhabited from the 1970s onward — that overlaps significantly with the documented Epstein social network of the 1990s and early 2000s.</p>
<p>Prominent among the accusers beyond Carroll: Summer Zervos, a former contestant on <em>The Apprentice</em>, alleged Trump groped her in a hotel room in 2007 and filed a defamation suit in New York in 2017 when Trump denied her account. The case was ultimately resolved in 2022 after years of litigation over whether a sitting president could be subject to civil process. Kristin Anderson, a former model, told The Washington Post in October 2016 that Trump had groped her in a Manhattan nightclub in the early 1990s. Her account was corroborated by a witness who was present. Jessica Leeds told The New York Times in 2016 that Trump had groped her on an airplane in the late 1970s.</p>
<h2>The Standard of Accountability</h2>
<p>In a functioning democracy, the question of who holds public office is inseparable from the question of what that person has done and what they are credibly alleged to have done. The legal record described in this article is part of the public record of the United States. Jury verdicts are not opinions; they are findings of fact by citizens exercising one of the most fundamental duties of democratic society. Two such verdicts, in two separate proceedings, have found Trump liable for sexual abuse and defamation. The obligation of journalism is to ensure that this record is not suppressed, minimized, or forgotten — and that those in positions of public trust are held to a standard of accountability that their power would otherwise allow them to avoid.</p>
<div class="sources"><strong>Sources:</strong> Carroll v. Trump, SDNY (2023 liability verdict; 2024 damages verdict); Jane Doe v. Donald J. Trump and Jeffrey E. Epstein, SDNY case 1:16-cv-07673 (2016); sworn declarations filed in connection with the 2016 federal complaint; The New York Times comprehensive accounting of Trump accusers (October 2016 and updated 2023); The Washington Post reporting on Kristin Anderson (October 2016); Summer Zervos v. Trump, New York courts (2017-2022); reporting by The Atlantic and New York Magazine.</div>"""

a10_content = a10_figure + a10_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 11: new-article-006 — Bill Gates and Epstein
# ─────────────────────────────────────────────────────────────────────────────
a11_figure = '<figure><img src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80" alt="Bill Gates" /><figcaption>Bill Gates, co-founder of Microsoft and co-chair of the Bill and Melinda Gates Foundation, met with Jeffrey Epstein on multiple documented occasions after Epstein\'s 2008 sex offense conviction. Gates has called the meetings "a mistake." Credit: World Economic Forum / CC BY-SA 2.0</figcaption></figure>'

a11_body = """
<h2>The Meetings That Should Not Have Happened</h2>
<p>In September 2019, The New York Times published a major investigation into the relationship between Bill Gates and Jeffrey Epstein — reporting based on interviews with more than a dozen current and former employees, financial records, and correspondence. The investigation documented that Gates had met with Epstein on multiple occasions between approximately 2011 and 2014, after Epstein's 2008 conviction in Florida for soliciting prostitution from a minor — a conviction that had made Epstein a registered sex offender and had generated substantial national reporting about his history of abuse.</p>
<p>The meetings took place primarily at Epstein's nine-story Manhattan townhouse at 9 East 71st Street — a property that had been transferred to Epstein by retail billionaire Les Wexner under circumstances that federal prosecutors later described as involving Epstein's exploitation of Wexner's trust. The townhouse was, by the time of these meetings, well established in the public record as the site of Epstein's most serious documented abuses. Multiple victims had described it in sworn depositions. The Palm Beach Post and other Florida outlets had covered Epstein's criminal case in detail. Gates was among the most closely observed individuals in the world. He chose to go there.</p>
<p>Gates acknowledged the meetings. He described them as related to a proposed philanthropic fund — a potential $10 billion initiative for global health that he was attempting to establish and that Epstein, who claimed extensive connections to wealthy financiers, had represented he could help with. Gates subsequently called the meetings "a mistake" and expressed regret for the association. The acknowledgment generated more questions than it resolved.</p>
<h2>What the Documented Record Shows</h2>
<p>The New York Times investigation, confirmed in subsequent reporting by The Wall Street Journal, Bloomberg, and other outlets, documented the following:</p>
<ul>
<li>Gates met with Epstein at the Manhattan townhouse on multiple occasions between 2011 and 2014, with multiple current and former Gates employees confirming they had been present at or aware of these meetings</li>
<li>At least one meeting included senior executives from JPMorgan Chase whom Epstein had arranged as potential philanthropic contacts</li>
<li>Gates flew on a plane that Epstein had arranged, a point Gates's representatives described as involving a chartered aircraft rather than Epstein's personal plane — a distinction that journalists who reviewed the available records have disputed</li>
<li>Boris Nikolic, a former chief science advisor to Gates who attended Gates-Epstein meetings, was named in Epstein's will as a contingent executor — a designation Nikolic stated he had been unaware of and declined to accept, but which indicated Epstein considered him part of his trusted network</li>
<li>Internal emails obtained by The Times showed Gates employees discussing the meetings and their concerns about the association — suggesting awareness within the Gates organization that the relationship was problematic even as it continued</li>
</ul>

<figure><img src="https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80" alt="Philanthropy and power" /><figcaption>The Gates Foundation, with an endowment of approximately $70 billion, is the largest private funder of the World Health Organization — raising structural questions about the accountability of private philanthropic power over global public health policy. Credit: Wikimedia Commons</figcaption></figure>

<h2>Melinda Gates and the Epstein Factor</h2>
<p>The Wall Street Journal, in its reporting on the divorce proceedings between Bill and Melinda Gates in 2021, documented that Melinda Gates had raised concerns about the Epstein relationship as early as 2013 — several years before it became public. According to people familiar with the situation quoted by The Journal, Melinda Gates met with divorce attorneys in 2019 to begin planning for a potential divorce, and the Epstein association was described as a significant factor in her decision-making. The Gateses divorced in May 2021 after 27 years of marriage.</p>
<p>Gates has not offered a complete accounting of what precisely Epstein offered that he found valuable enough to justify multiple visits to a convicted sex offender's home. The philanthropic fundraising explanation — that Epstein claimed he could connect Gates to major donors for a global health fund — has been received skeptically by people familiar with the Gates Foundation's actual fundraising operations, who note that Gates had ample access to major donors through his own network without needing Epstein's facilitation.</p>
<h2>The Structural Question: Power Without Accountability</h2>
<p>The fundamental issue raised by the Gates-Epstein association is not primarily whether Gates committed any crime — there is no credible evidence that he did. The issue is what the association reveals about how extreme wealth insulates its possessors from the social and professional consequences that would affect anyone else. A person of ordinary means who pursued a friendship with a convicted child sex offender — meeting repeatedly at that person's home after the conviction, discussing business arrangements — would face immediate and severe professional and social consequences. Gates faced almost none until the relationship was reported by The Times in 2019.</p>
<p>The Epstein association exists within a broader context of questions about the Gates Foundation's accountability. The Foundation has an endowment of approximately $70 billion and is the single largest private donor to the World Health Organization, in some years contributing more than any single nation-state to the WHO's budget. It has committed billions to vaccine development, agricultural reform, and public health infrastructure across the developing world. These are not small things. But they are decisions being made by a private institution controlled by a single family, without the democratic accountability that governs public funding of comparable scale.</p>
<h2>The Accountability That Wealth Prevents</h2>
<p>When The New York Times published its investigation in 2019, Epstein was already in custody. Gates was not in a position of legal vulnerability. His acknowledgment of the meetings as "a mistake" and his expressions of regret were accepted by most media organizations as sufficient. No formal investigation of the relationship was opened by any law enforcement body. The Gates Foundation's public work continued. His public reputation, while affected by the reporting and by the subsequent divorce, remained substantially intact.</p>
<p>The question the Epstein-Gates association poses is ultimately the same question the entire Epstein case poses: what does it mean that the most powerful people in American life could associate with a convicted sex trafficker for years — in some cases meeting him repeatedly at his own home after his conviction — and face effectively no consequence? The answer is not obscure. It is the answer that the Epstein case as a whole provides, again and again, in different institutional settings: that the protections available to the extremely powerful are qualitatively different from those available to everyone else, and that the systems of accountability designed to check that power have proven, in this as in other cases, inadequate to the task.</p>
<div class="sources"><strong>Sources:</strong> The New York Times, "Bill Gates Met With Jeffrey Epstein Many Times, Despite His Criminal Past" (September 2019); The Wall Street Journal reporting on Gates divorce and Epstein concerns (2021); Bloomberg reporting on Gates-Epstein meetings; Gates Foundation public financial disclosures; reporting by The Guardian and ProPublica on Gates Foundation global health influence; Boris Nikolic public statement declining executor role (2019).</div>"""

a11_content = a11_figure + a11_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 12: new-article-007 — Ghislaine Maxwell
# ─────────────────────────────────────────────────────────────────────────────
a12_figure = '<figure><img src="https://images.unsplash.com/photo-1505664173692-dbceb18146fc?auto=format&fit=crop&w=800&q=80" alt="Ghislaine Maxwell booking photo" /><figcaption>Ghislaine Maxwell — booking photograph taken at the Metropolitan Detention Center, Brooklyn, following her July 2020 arrest. She was convicted in December 2021 on five federal counts including sex trafficking of a minor. She is serving a 20-year sentence. Credit: U.S. Department of Justice / Public Domain</figcaption></figure>'

a12_body = """
<h2>The Woman at the Center</h2>
<p>No individual is more central to understanding the full scope of Jeffrey Epstein's criminal enterprise than Ghislaine Maxwell. His companion for years, his social facilitator, and by federal prosecutors' own account his most essential operational partner, Maxwell was present at virtually every documented phase of Epstein's criminal activity across more than two decades. She recruited victims — often by presenting herself as a glamorous, well-connected woman who could advance their careers. She groomed them through a process designed to normalize Epstein's demands. She participated directly in the abuse in some instances. And she coordinated the logistics of a trafficking operation that spanned multiple countries, multiple properties, and two decades of deliberate predation.</p>
<p>She is now serving a 20-year federal prison sentence at FCI Tallahassee, a federal correctional institution in Florida. She has said almost nothing that has helped accountability reach anyone other than herself.</p>
<h2>Background: The Heiress and the Mogul</h2>
<p>Ghislaine Maxwell was born in 1961, the youngest daughter of Robert Maxwell — the British media magnate, Member of Parliament, and suspected intelligence operative whose business empire at its peak included newspapers, television, publishing, and data services across Europe and North America. Her father's November 1991 death — he was found floating in the Atlantic Ocean near his yacht, having fallen or been pushed overboard under circumstances that remain officially unexplained — left the family financially ruined. His companies were found to be insolvent, his pension funds looted, and his public reputation destroyed.</p>
<p>It was in the years following Robert Maxwell's death that his youngest daughter's relationship with Jeffrey Epstein deepened from social acquaintance to something far more integral. Epstein provided Ghislaine with financial support, properties to inhabit, and social access to a world that her father's fall had seemed to close off. In exchange, she provided what was essential to Epstein's operation: recruitment networks built from her family's social connections across British, European, and American elite society; the credibility of a famous surname; and the operational energy of someone who was, by multiple accounts, genuinely committed to the enterprise.</p>
<h2>The Federal Trial: What Prosecutors Proved</h2>
<p>At Maxwell's December 2021 federal trial in the Southern District of New York, prosecutors called four women — identified at trial as "Jane," "Kate," "Carolyn," and Annie Farmer — who testified about their experiences as victims of Epstein's network while Maxwell was present and complicit. The jury deliberated for approximately six days before convicting Maxwell on five of six counts. The verdicts:</p>
<ul>
<li><strong>Conspiracy to entice minors to travel to engage in illegal sex acts:</strong> Guilty</li>
<li><strong>Enticement of a minor to travel to engage in illegal sex acts:</strong> Guilty</li>
<li><strong>Conspiracy to transport minors with intent to engage in criminal sexual activity:</strong> Guilty</li>
<li><strong>Transportation of a minor with intent to engage in criminal sexual activity:</strong> Guilty</li>
<li><strong>Sex trafficking of a minor:</strong> Guilty</li>
</ul>
<p>Trial testimony established that Maxwell actively recruited victims through a process designed to appear benign. She approached young women — often girls — in public settings, presented herself warmly, offered gifts, trips, and educational or professional opportunities, and used those inducements to create relationships that were progressively used to normalize sexual contact with Epstein. Several witnesses testified that Maxwell participated directly in sexual acts. Others testified that she was present during Epstein's abuse without intervening.</p>

<figure><img src="https://images.unsplash.com/photo-1577083165350-14c11b1f6db5?auto=format&fit=crop&w=800&q=80" alt="Jeffrey Epstein mugshot" /><figcaption>Jeffrey Epstein, Maxwell's partner in the trafficking enterprise. Maxwell's 2021 conviction established the systematic nature of the operation they ran together — but prosecutors have indicated that Maxwell's knowledge extends well beyond what was introduced at trial. Credit: Palm Beach County Sheriff's Office / Public Domain</figcaption></figure>

<h2>The Names She Hasn't Given</h2>
<p>Throughout her prosecution, speculation centered on whether Maxwell would cooperate with federal prosecutors in exchange for a reduced sentence. She did not. Post-conviction reporting indicated that discussions about cooperation had occurred but produced no agreement. Maxwell was sentenced to 20 years in prison by Judge Alison Nathan in June 2022. During sentencing, Maxwell stated: "I empathize deeply with every victim." It was among the most pro forma statements of remorse in a proceeding characterized by its absence of genuine accountability.</p>
<p>What Maxwell could offer prosecutors is substantial. She was, by every credible account, the person who knew the network's full scope — not just the victims and the logistics, but the men who used the trafficking system she created, the compromising material that was collected, the network of protection that allowed the operation to continue for decades, and the identities of anyone who was aware of the trafficking and chose silence over intervention. Her knowledge, if made fully available to law enforcement, could plausibly lead to the prosecution of additional individuals whose wealth and connections have thus far insulated them from accountability.</p>
<p>Virginia Giuffre, the most prominent of Epstein's victims and the woman whose civil litigation has been the most consequential in the case, alleged in sworn depositions that she was trafficked to multiple well-known men, including Prince Andrew, Duke of York. Andrew settled Giuffre's civil lawsuit in February 2022 for a sum widely reported to be in the tens of millions of pounds, without admitting liability. His relationship with Maxwell and Epstein, documented in photographs and in Giuffre's sworn testimony, has ended his active royal duties.</p>
<h2>The Sentencing and Its Meaning</h2>
<p>Judge Nathan's imposition of a 20-year sentence was described by victims' advocates as significant but inadequate. The maximum sentence Maxwell faced on the counts of conviction was 65 years. The prosecution sought 30 to 55 years. Maxwell was 60 years old at sentencing. With good-time reductions, she could be eligible for release in her late 70s — having spent approximately 17 years in prison for crimes that enabled decades of sexual abuse of minors and that, by the evidence introduced at trial, she committed with full knowledge and deliberate organizational skill.</p>
<p>For Epstein's victims, Maxwell's sentence and her continued silence represent a profound and ongoing injustice. The promise that was implicit in her arrest and conviction — that the full truth of what happened would eventually be told, that the men who participated would be held accountable — remains unkept. Maxwell knows what happened. She has chosen not to say. Whether that calculation holds through two more decades of imprisonment, or whether cooperation at some future point remains possible, is known only to her and to the prosecutors who may or may not continue to extend the offer.</p>
<div class="sources"><strong>Sources:</strong> U.S. v. Ghislaine Maxwell, SDNY trial record and jury verdict (December 2021); sentencing hearing transcript (June 2022); Virginia Giuffre v. Ghislaine Maxwell civil deposition excerpts (partially unsealed by court order, 2022-2024); Giuffre v. Prince Andrew settlement (February 2022); reporting by The Guardian, The Miami Herald, The New York Times, and The New Yorker; Maxwell's Daily Mail prison interview (2021).</div>"""

a12_content = a12_figure + a12_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 13: new-article-008 — Little St. James Island
# ─────────────────────────────────────────────────────────────────────────────
a13_figure = '<figure><img src="https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=800&q=80" alt="Jeffrey Epstein" /><figcaption>Jeffrey Epstein purchased Little St. James Island in the U.S. Virgin Islands in 1998 for $7.95 million and invested an estimated $200 million developing it into what prosecutors described as the physical center of his sex trafficking operation. Credit: Palm Beach County Sheriff\'s Office / Public Domain</figcaption></figure>'

a13_body = """
<h2>The Island That Nobody Was Supposed to Talk About</h2>
<p>Little St. James is a 75-acre private island in the U.S. Virgin Islands, situated approximately one mile off the southeastern coast of St. Thomas. Jeffrey Epstein purchased it in 1998 for $7.95 million. By the time of his 2019 arrest, he had invested an estimated $200 million in its development and maintenance. The island included a main residence, multiple guest and staff cottages, a library, a music pavilion, a helipad, multiple private beaches, and a network of infrastructure — roads, utilities, a desalination plant — that made it fully self-contained. It was, in every physical and operational sense, a world unto itself.</p>
<p>For more than two decades, Little St. James served as what federal prosecutors described as the physical epicenter of Epstein's criminal enterprise. It was where some of the most serious documented abuses occurred. It was where some of the most powerful people in the world traveled, aboard private aircraft, to a location where no one outside Epstein's control could observe their arrival or departure. And it was where, by the sworn testimony of multiple victims and former employees, the ordinary constraints that governed the behavior of powerful people in the rest of the world were effectively suspended.</p>
<h2>The Architecture of Isolation</h2>
<p>The island's geography was fundamental to its function. Its remoteness made unauthorized access essentially impossible. Its private ownership meant that law enforcement could not enter without Epstein's consent or a valid search warrant — and obtaining a warrant for a private island owned by a man with demonstrated capacity to manage federal prosecutors had, for years, proven beyond the reach of investigators who had otherwise built a substantial case against him.</p>
<p>Access to the island was controlled entirely by Epstein. Visitors arrived by boat from St. Thomas — a journey of approximately 15 minutes — or by helicopter directly to the island's helipad. Both modes of arrival required Epstein's invitation or, for any uninvited approach, would be detected by the island's security systems. The island's communications — phone and internet — were, by multiple accounts, monitored or controlled in ways that limited unobserved contact between the young women present and the outside world.</p>
<p>Multiple former employees and victims have described the island's security arrangements as extensive. Surveillance cameras covered approaches to the island and significant portions of its interior. Former staff described equipment they were instructed never to touch, rooms they were told to avoid, and areas of the island to which only Epstein and Maxwell had unrestricted access. This infrastructure served multiple functions: security, control, and — according to legal theories advanced by civil attorneys for Epstein's victims — the collection and storage of compromising material on guests.</p>
<h2>What Victims Testified Under Oath</h2>
<p>Multiple women who testified in civil proceedings and at Ghislaine Maxwell's 2021 federal trial described their experiences on the island in sworn accounts that share a consistent structural pattern across individual differences in detail:</p>
<ul>
<li>Arrival by private jet or boat, with passports sometimes held by staff upon arrival — a documented practice that materially impeded any independent departure</li>
<li>Immediate integration into a scheduled routine of "work" — described as massage but understood, through the grooming Maxwell had conducted in advance, to encompass sexual contact with Epstein and, on some occasions, with other men Epstein directed them toward</li>
<li>The presence of other young women in similar situations, creating a social environment in which compliance appeared normalized through apparent collective acceptance — a dynamic prosecutors described as a deliberate feature of the operation</li>
<li>Sightings of prominent individuals at the island — politicians, businessmen, academics, foreign dignitaries — whose presence created the impression that participation in Epstein's world was something powerful people accepted as ordinary</li>
<li>A clear understanding that independent departure was not possible without Epstein's assistance, and that the consequences of telling anyone about what had occurred would be serious</li>
</ul>

<figure><img src="https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80" alt="US Virgin Islands" /><figcaption>The U.S. Virgin Islands government pursued civil action against Epstein's estate and settled for $105 million in 2024 — one of the largest settlements in the entire Epstein case. USVI officials provided significant tax incentives to Epstein during his operation of Little St. James. Credit: Wikimedia Commons</figcaption></figure>

<h2>The Structure on the Hill</h2>
<p>Among the most widely discussed and least officially investigated features of Little St. James is the structure that aerial photography shows positioned on an elevated point at one end of the island. Widely described in media coverage as a "temple," the building was constructed in blue and white stripes and topped, in earlier aerial photographs, with what appeared to be a gold dome. Subsequent aerial photography documented changes to the structure, including what appeared to be the removal of the dome and construction activity on its exterior.</p>
<p>Former employees interviewed by journalists gave varying accounts of the building's function, ranging from a music room to a guest facility to a storage structure. None offered an account that explained its distinctive architecture, its elevated and conspicuous placement, or the tight restrictions that reportedly governed access to it. The building has never been officially inspected or documented by any law enforcement agency. Whatever physical evidence it might have contained was subject to the same access and preservation challenges that characterized the rest of the island's evidence.</p>
<h2>The U.S. Virgin Islands Connection</h2>
<p>The USVI government's relationship with Epstein was itself a subject of significant litigation. Epstein's companies — registered in the Virgin Islands as JEGE Inc. and Nautilus Inc. — received millions of dollars in economic development tax credits and incentives from the USVI government, reducing his tax burden by amounts that investigators estimated in the tens of millions of dollars over the period of the operation. The grants were described by the USVI Attorney General's office, in its subsequent lawsuit against Epstein's estate, as having been fraudulently obtained.</p>
<p>The USVI filed a civil action against the Epstein estate in 2020, alleging that Epstein had used the island as a base for sex trafficking and that the tax incentives awarded to him had effectively subsidized the operation. The suit was settled in November 2024 for $105 million — one of the largest single settlements in the entire Epstein litigation. The settlement included requirements for cooperation with ongoing investigations and documentation of the estate's assets.</p>
<h2>The Cleanup and the Question of Evidence</h2>
<p>Following Epstein's July 2019 arrest in New Jersey, investigators sought access to his properties including Little St. James. The island had been maintained by a staff of employees for weeks between Epstein's arrest and the first law enforcement inspection. Multiple journalists and civil attorneys have raised the question of what may have been removed, altered, or cleaned during that interval — physical evidence, digital records, or other materials whose destruction or removal would have served the interests of the many individuals whose association with the island they had reason to want kept private.</p>
<p>These allegations have not been resolved by any official finding. They reflect a broader concern about the preservation of evidence across the entire Epstein case — a concern that is not speculative but grounded in documented patterns of evidence management, from the handling of surveillance footage at the MCC to the logistics of the 2008 non-prosecution agreement. Little St. James remains the most tangible physical monument to what Jeffrey Epstein built. Its full secrets remain, like so much of this case, incompletely known.</p>
<div class="sources"><strong>Sources:</strong> Trial testimony from U.S. v. Maxwell (2021); civil deposition excerpts from Giuffre v. Maxwell, partially unsealed by court order; Miami Herald "Perversion of Justice" series by Julie K. Brown (2018-2019); USVI Attorney General civil suit against Epstein estate and $105 million settlement (2024); aerial photography documentation of Little St. James available through published reporting; reporting by The New York Times, The Guardian, and The Daily Beast.</div>"""

a13_content = a13_figure + a13_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 14: new-article-009 — The Acosta Deal
# ─────────────────────────────────────────────────────────────────────────────
a14_figure = '<figure><img src="https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80" alt="US Capitol building" /><figcaption>Congressional oversight hearings on the Epstein non-prosecution agreement in July 2019 led to the resignation of Labor Secretary Alexander Acosta, who had negotiated the agreement as U.S. Attorney for the Southern District of Florida in 2008. Credit: Wikimedia Commons</figcaption></figure>'

a14_body = """
<h2>The Deal That Should Never Have Been Made</h2>
<p>In September 2007, after nearly two years of investigation by the FBI's Miami field office — an investigation that had identified at least 36 underage victims of Jeffrey Epstein's sexual abuse and generated a 53-page federal draft indictment recommending charges that could have resulted in a life sentence — federal prosecutors in the Southern District of Florida elected not to file. Instead, over the following months, they negotiated a plea agreement that remains one of the most consequential and controversial prosecutorial decisions in recent American legal history.</p>
<p>The outcome: Epstein pleaded guilty to two state-level charges in Palm Beach County — soliciting prostitution and soliciting prostitution from a minor. He received an 18-month sentence in county jail. Work release privileges allowed him to leave custody for up to 12 hours per day, six days per week, to conduct business from his Palm Beach office. He served approximately 13 months before release on community control. He registered as a sex offender in Florida and continued, in the years that followed, to operate with substantially the same freedom he had enjoyed before his arrest.</p>
<p>In exchange for this extraordinary resolution: all federal criminal charges were dropped. Immunity from federal prosecution was extended not only to Epstein himself but, in the agreement's remarkable language, to "any potential co-conspirators" — unnamed individuals who had facilitated his crimes. The victims were not informed the agreement was being negotiated. They were not given the opportunity to object to its terms. Their rights under federal law were violated, a federal court later found, as a matter of deliberate prosecutorial choice.</p>
<h2>The Architect</h2>
<p>Alexander Acosta was the U.S. Attorney for the Southern District of Florida at the time of the negotiations — a Harvard Law graduate, a member of the Federalist Society, and one of the most prominent federal prosecutors in the country. The decision to offer Epstein the non-prosecution agreement was made over the specific objections of career prosecutors in his office who had built the case and believed the evidence supported far more serious federal charges. Those prosecutors' objections were noted in internal communications that were later made public through litigation.</p>
<p>In 2017, Trump appointed Acosta Secretary of Labor. He served for two years before the Miami Herald's 2018 reporting forced the agreement back into public view and produced the political pressure that led to his July 2019 resignation. At a press conference on July 10, 2019 — his final public appearance in that role — Acosta made the statement that has haunted the public discussion of the case ever since: that he had been told by persons he did not name that Epstein "belonged to intelligence" and to "stand down." He resigned the following day without elaborating on this claim.</p>
<h2>The Julie Brown Investigation and What It Found</h2>
<p>The Miami Herald's "Perversion of Justice" series, published in November 2018 and reported by Julie K. Brown, was the most significant single act of journalism in the Epstein case. Based on years of reporting, hundreds of interviews, and review of thousands of pages of documents obtained through public records requests and litigation, Brown's series established the following as matters of documented public record:</p>
<ul>
<li>The non-prosecution agreement had been negotiated in secret over many months, with Epstein's legal team — which included former Whitewater independent counsel Ken Starr and Harvard Law professor emeritus Alan Dershowitz — having significant input into the final terms</li>
<li>The agreement had been deliberately concealed from Epstein's victims, in violation of the Crime Victims' Rights Act of 2004 — a finding later confirmed by Federal Judge Kenneth Marra in a February 2019 opinion</li>
<li>The career prosecutors who had built the case were effectively sidelined from the final negotiations, which were conducted at the U.S. Attorney level with Epstein's senior defense counsel</li>
<li>The immunity provision extending protection to unnamed co-conspirators was drafted in unusually broad language that went beyond what is standard in plea agreements and effectively foreclosed prosecution of anyone in Epstein's network</li>
<li>The work release conditions — 12 hours per day, six days per week — were the result of negotiations between Epstein's attorneys and the Palm Beach County Sheriff's office that were approved at multiple levels without the kind of scrutiny that would have been applied to any ordinary defendant</li>
</ul>

<figure><img src="https://images.unsplash.com/photo-1505664173692-dbceb18146fc?auto=format&fit=crop&w=800&q=80" alt="The White House" /><figcaption>Alexander Acosta was appointed Secretary of Labor by President Trump in 2017 and resigned in July 2019 following renewed public attention on the Epstein agreement he had negotiated nine years earlier. Credit: Wikimedia Commons</figcaption></figure>

<h2>The Court Found a Crime Victims' Rights Violation</h2>
<p>On February 21, 2019, Federal Judge Kenneth Marra issued a ruling in Doe v. United States that is among the most significant in the entire legal history of the Epstein case. Judge Marra found that the Justice Department had violated the Crime Victims' Rights Act by concealing the non-prosecution agreement from Epstein's victims — not through inadvertence or oversight, but deliberately, because the prosecutors were aware that informing the victims would have given them the right to object to its terms and might have jeopardized the agreement entirely.</p>
<p>Judge Marra found that prosecutors had engaged in "a conspiracy of silence" with Epstein's legal team that deliberately excluded the victims from a process that the law required to include them. His ruling did not — could not — undo the agreement itself or restore the federal charges that had been dropped. But it established, as a matter of federal judicial finding, that the agreement had been obtained through a process that violated the rights of Epstein's victims and was inconsistent with the obligations of federal prosecutors.</p>
<h2>What the Agreement Cost</h2>
<p>The cost of the Acosta deal is calculable in specific human terms. In the decade between the 2008 agreement and Epstein's 2019 federal arrest, Epstein continued to operate. The conditions that enabled his crimes — freedom, resources, social access, protection from serious legal scrutiny — remained substantially intact. The women who were victimized during those additional years would not have been victimized had the federal indictment been filed and Epstein been sentenced to the decades in prison the evidence supported.</p>
<p>The immunity granted to unnamed co-conspirators has never been officially inventoried. No public accounting exists of who it protected, what they did, or whether it foreclosed prosecutions that might otherwise have been possible. The names of those co-conspirators remain hidden behind the agreement's deliberately vague language. The Acosta deal, struck in secret in 2008, continues in 2026 to shape the boundaries of what accountability is legally possible for everyone who participated in Jeffrey Epstein's network.</p>
<div class="sources"><strong>Sources:</strong> Miami Herald, Julie K. Brown, "Perversion of Justice" series (November 2018); Judge Kenneth Marra opinion in Doe v. United States finding CVRA violation (February 21, 2019); non-prosecution agreement text, released through litigation; Acosta press conference transcript (July 10, 2019); Palm Beach Police Department investigation records released through public records litigation; Brown, <em>Perversion of Justice</em> (2021); reporting by ProPublica on Acosta appointment and resignation.</div>"""

a14_content = a14_figure + a14_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 15: new-article-010 — The Network of Mutual Compromise
# ─────────────────────────────────────────────────────────────────────────────
a15_figure = '<figure><img src="https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=800&q=80" alt="Jeffrey Epstein 2008 mugshot" /><figcaption>Jeffrey Epstein — whose criminal operation relied as much on blackmail and mutual compromise as on the direct abuse that has been prosecuted. The full extent of what he collected and who it protected remains unknown. Credit: Palm Beach County Sheriff\'s Office / Public Domain</figcaption></figure>'

a15_body = """
<h2>A New Kind of Power</h2>
<p>Jeffrey Epstein's operational insight — if one can invoke that word without endorsing its application — was his understanding that in a world where power protects power, the most durable form of leverage is the information that the powerful most urgently want suppressed. Financial wealth can be lost. Social standing can erode. Political power can be voted away. But compromising information, held by someone with both the material means and the will to deploy it, creates a form of mutual dependency that is remarkably stable across time and circumstance.</p>
<p>Epstein was not, by the standards of the world he inhabited, extraordinarily wealthy. He was not a political figure. He did not hold institutional power in the conventional sense. What he built instead was a system in which powerful men's participation in his network generated the conditions for their own control. The invitation to his island, to his parties, to his social world was also, in a real structural sense, an invitation to mutual vulnerability — an invitation that many of the most powerful people in American and international life accepted.</p>
<h2>The Surveillance Infrastructure</h2>
<p>Multiple former employees, civil attorneys representing Epstein's victims, and investigators who worked the case have described an elaborate surveillance system installed at Epstein's primary properties. Hidden cameras in guest rooms and common areas were described by multiple witnesses in depositions and at Maxwell's 2021 federal trial. Former employees described being told not to enter specific rooms, not to disturb equipment in certain areas, and not to discuss what they observed on the properties with anyone outside.</p>
<p>The legal theory advanced by attorneys representing Epstein's victims — including David Boies, whose firm has represented Virginia Giuffre and other accusers — is that this surveillance infrastructure was not primarily for security purposes. Its primary function, in Boies's legal framing and that of other plaintiffs' attorneys, was the collection and preservation of compromising material on guests who were brought to the properties. If correct, this reframes the entire structure of what Epstein was doing: not merely a sex offender with powerful friends, but the operator of what may have been the most extensive private intelligence-collection and blackmail operation in American history — one in which access to young women was simultaneously the direct commodity and the mechanism for collecting leverage over the men who consumed that commodity.</p>
<h2>The Documented Participants</h2>
<p>The individuals who have been documented through flight logs, visitor records, civil depositions, trial testimony, or their own public statements as having had contact with Epstein's network include some of the most prominent people in American and international public life. In almost every case, the legal and professional consequences they faced were modest relative to the documented facts of their association:</p>
<p><strong>Prince Andrew, Duke of York:</strong> Virginia Giuffre alleged in sworn depositions that she was trafficked to Andrew by Epstein and Maxwell on multiple occasions when she was 17 years old. Photographs published by media organizations showed Andrew with his arm around Giuffre's waist, with Maxwell visible in the background — photographs Andrew claimed he could not explain and attempted to cast doubt on through a widely ridiculed television interview in November 2019. He settled Giuffre's civil lawsuit in February 2022 for a sum reported to be in the tens of millions of pounds, without admitting liability. He was subsequently stripped of his royal military roles and public duties. He has not been criminally charged.</p>
<p><strong>Les Wexner:</strong> The Ohio retail billionaire and founder of L Brands — parent company of Victoria's Secret and Bath and Body Works — was Epstein's primary financial patron across the period of his most serious criminal activity. Wexner transferred his nine-story Manhattan townhouse to Epstein, granted him broad power of attorney over his financial affairs, and maintained their association for years while, Wexner later claimed, being entirely unaware of Epstein's criminal conduct. Wexner stated publicly that Epstein had "misappropriated vast sums of money" from him and that he had been "deceived and betrayed." He stepped down as CEO of L Brands in 2020 amid significant public pressure. He has not been charged with any crime. The extent of his actual knowledge of Epstein's activities during the period of their close financial relationship has never been established in any legal proceeding.</p>
<p><strong>Alan Dershowitz:</strong> The Harvard Law professor emeritus and prominent criminal defense attorney, who was among Epstein's defense team during the 2008 plea negotiations, was named by Virginia Giuffre in a 2015 civil filing as among the men to whom she was trafficked. Dershowitz has denied all allegations with extraordinary persistence — filing defamation suits, writing books, and maintaining a continuous public campaign to discredit Giuffre and others who have made claims against him. The litigation between Dershowitz and Giuffre produced extensive filings but no verdict on the factual allegations as of this writing. Dershowitz has not been charged with any crime.</p>

<figure><img src="https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&w=800&q=80" alt="Private island aerial view" /><figcaption>Ghislaine Maxwell's 2021 conviction established that the Epstein trafficking network was systematic and institutional — not the work of a lone predator but of an organized enterprise with multiple participants, managed logistics, and sustained layers of protection from accountability. Credit: U.S. Department of Justice</figcaption></figure>

<h2>JPMorgan, Deutsche Bank, and the Financial Enablers</h2>
<p>The financial institutions that maintained business relationships with Epstein after his 2008 conviction became subjects of civil litigation that produced significant settlements. JPMorgan Chase maintained Epstein as a client for years after his conviction, processing transactions totaling hundreds of millions of dollars through accounts the bank's own internal compliance systems had flagged. The U.S. Virgin Islands and Giuffre's attorneys sued JPMorgan, alleging that the bank had facilitated Epstein's trafficking through the financial services it provided. JPMorgan settled the USVI lawsuit for $75 million in 2023 and a related private lawsuit for $290 million in 2023 — the largest single financial settlement arising directly from the Epstein case. Deutsche Bank, which took over some of Epstein's financial relationships after JPMorgan ended them, settled a related case for $75 million in 2023.</p>
<p>These settlements, while they involved no admission of wrongdoing, represent judicial findings that the allegations were sufficiently credible to warrant significant financial resolution. They also represent the only instance in the entire Epstein case where institutions with substantial resources and sophisticated risk management systems — institutions that had access to information about Epstein's criminal history and whose compliance departments had flagged his transactions — faced concrete financial consequences for their decisions to continue serving him.</p>
<h2>The Intelligence Hypothesis</h2>
<p>The most significant and least resolved question in the entire Epstein case is the one Acosta himself raised: whether Epstein operated with the knowledge, support, or direction of any U.S. or foreign intelligence agency, and whether compromising material he collected was shared with or directed by such an agency.</p>
<p>Former CIA officer Robert Baer stated publicly that Epstein's operation bore the hallmarks of an intelligence-gathering enterprise — specifically, the systematic collection of compromising material on powerful individuals, which is known in intelligence tradecraft as "kompromat." Attorney David Boies has said in published interviews that based on his knowledge of the case, he believes Epstein was operating as some form of intelligence asset, though he has stopped short of specifying which agency. Journalist Vicky Ward, who has reported on the Epstein case for more than two decades, has documented the evidence for this hypothesis in detail in her book <em>Chasing Epstein</em>.</p>
<p>This hypothesis has not been proven. No documentary evidence establishing a formal relationship between Epstein and any intelligence agency has entered the public record. Acosta's claim — "I was told Epstein belonged to intelligence, to stand down" — is the most direct on-the-record statement, and it comes from the man who made the agreement that protected Epstein from federal prosecution. It remains unresolved, uninvestigated by any public body with the authority and access to investigate it, and therefore not answered.</p>
<h2>Why It Lasted as Long as It Did</h2>
<p>The most important question in the Epstein case is not who he was or what he did. Those facts are substantially documented. The important question is how he was able to do it for more than two decades — across multiple jurisdictions, involving dozens of powerful adults who knew or had every reason to know what was happening — without being stopped. The answer, assembled from the available public record, is that the system functioned precisely as he designed it: the powerful people in his orbit had reasons to stay silent; the prosecutors who could have stopped him had reasons, whether personal, professional, or external, to proceed with restraint; the investigators who built the case found their work undermined by decisions made above their level; and the victims — young, often marginalized, without resources or connections — were the last priority of institutions that were nominally designed to protect them. Understanding those systems — naming them, documenting them, and refusing to allow them to be buried beneath the passage of time and the density of the public record — is the work that remains.</p>
<div class="sources"><strong>Sources:</strong> Virginia Giuffre v. Prince Andrew settlement (February 2022); U.S. v. Maxwell trial record (2021); JPMorgan Chase settlement with USVI and related parties ($75M and $290M, 2023); Deutsche Bank settlement ($75M, 2023); civil deposition excerpts from Giuffre v. Maxwell (partially unsealed, 2022-2024); Vicky Ward, <em>Chasing Epstein</em> (2021); Acosta press conference (July 10, 2019); reporting by The Miami Herald, The New Yorker, The New York Times, and The Guardian.</div>"""

a15_content = a15_figure + a15_body

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 16: a1b2c3d4 — Trump-Netanyahu Iran
# ─────────────────────────────────────────────────────────────────────────────
a16_content = """<h2>A Partnership Under Pressure</h2>
<p>For most of the modern era, the U.S.-Israel alliance has been characterized by its leaders as unbreakable — a relationship of shared values, shared security interests, and deep institutional ties that transcended changes in personnel at the top of either government. The relationship between Donald Trump and Israeli Prime Minister Benjamin Netanyahu appeared, during Trump's first term, to confirm that characterization. Trump moved the American embassy to Jerusalem. He recognized Israeli sovereignty over the Golan Heights. He withdrew the United States from the Iran nuclear agreement that Netanyahu had consistently opposed. The two leaders appeared to operate in unusual strategic alignment.</p>
<p><img src="https://images.unsplash.com/photo-1529101091764-c3526daf38fe?auto=format&fit=crop&w=800&q=80" alt="Diplomatic relations and geopolitical strategy concept" /></p>
<p>But beneath the publicly projected alignment, the documentary record of both Trump's first term and his return to power reveals a relationship more complicated than its public presentation — one defined, at its core, by genuinely divergent strategic calculations about the most consequential question in the Middle East: how to address Iran's nuclear program and its regional influence, and whether the answer requires military force.</p>
<h2>The Root of the Divergence: Iran</h2>
<p>Netanyahu's position on Iran has been consistent across decades and multiple Israeli governments: Iran represents an existential threat to Israel, its nuclear program must be permanently halted, and the appropriate response to a regime that has repeatedly promised Israel's destruction is maximum pressure backed by credible military threat. Netanyahu has at various points advocated openly for U.S. military action against Iranian nuclear facilities, and Israeli intelligence is widely believed to have conducted multiple covert operations against Iran's nuclear program, including the 2010 Stuxnet cyberattack, the assassination of Iranian nuclear scientists, and the 2021 Natanz facility attack.</p>
<p>Trump's approach to Iran has been more transactional. His maximum pressure campaign of economic sanctions during his first term was presented as a means of forcing Iran to the negotiating table for a more comprehensive deal than the one his predecessor had negotiated. But Trump's stated preference for deal-making over military action, his documented reluctance to engage in sustained military operations in the Middle East, and his publicly expressed skepticism about nation-building have created persistent tension with an Israeli security establishment that views diplomatic engagement with Iran as strategically naive.</p>
<h2>The 2020 Assassination and Its Aftermath</h2>
<p>The most significant moment of apparent strategic alignment between Trump and Netanyahu — and simultaneously one of the most consequential decisions of Trump's first term — was the January 2020 assassination of Iranian General Qasem Soleimani, commander of the Islamic Revolutionary Guard Corps' Quds Force, in a U.S. drone strike at Baghdad International Airport. Soleimani was the architect of Iran's regional military strategy and one of the most significant figures in the Iranian security establishment. His elimination was a goal that Israeli intelligence had long advocated for.</p>
<p>The strike was ordered by Trump following Iranian-backed militia attacks on U.S. military bases in Iraq. Its immediate consequence was a significant Iranian ballistic missile attack on U.S. forces in Iraq — an attack that resulted in traumatic brain injuries to more than 100 American service members. The longer-term consequence was a significant escalation of regional tensions without a clear diplomatic framework for managing them — exactly the kind of military action without strategic follow-through that has historically complicated U.S.-Israeli coordination.</p>
<h2>The Gaza War and Strategic Divergence</h2>
<p>The October 7, 2023 Hamas attack on Israel — the deadliest attack on Jews since the Holocaust, resulting in approximately 1,200 Israeli deaths and the taking of approximately 250 hostages — and the subsequent Israeli military campaign in Gaza created new and significant strains in the Trump-Netanyahu relationship as Trump returned to power in January 2025. Trump's stated priority was the return of the hostages and a ceasefire; Netanyahu's military and political calculus, shaped by the demands of his coalition and Israel's stated war aims, has sometimes diverged from a pace or form of resolution that Trump has publicly pushed for.</p>
<p>The divergence has been documented in reporting by The New York Times, The Wall Street Journal, and Israeli outlet Haaretz, which has cited current and former officials on both sides describing private communications that were significantly less warm than the public relationship suggested. Trump's statement in early 2025 that the hostage deal needed to happen "now" — and the reporting that followed about his frustration with Netanyahu's pace — reflected a dynamic that complicates the simple narrative of aligned allies.</p>
<h2>The Nuclear Question</h2>
<p>The most consequential dimension of the Trump-Netanyahu divergence concerns Iran's nuclear program. As of 2025, Iran is assessed by U.S., Israeli, and international intelligence to be within weeks of being able to produce enough enriched uranium for a nuclear weapon — the closest it has ever been. Netanyahu has consistently argued this represents the moment for decisive military action. Trump has, at various points, pursued diplomatic engagement with Iran, including direct communications with Iranian leadership about a potential new nuclear agreement.</p>
<p>The gap between these positions — military action versus negotiated constraint — is not merely tactical. It reflects fundamentally different assessments of what kind of Middle East is consistent with American interests, what the costs of a regional war would be for the United States, and whether any negotiated outcome with the Iranian government is achievable or durable. These are not questions with clear answers. They are questions whose resolution will define the strategic landscape of the Middle East for a generation.</p>
<h2>What the Alliance Requires</h2>
<p>The U.S.-Israel alliance has survived and will likely survive the specific tensions described in this article. Its institutional depth — in intelligence sharing, military cooperation, diplomatic coordination, and people-to-people ties — is more durable than the preferences of any individual leader. But the specific strategic divergence over Iran, and the broader divergence over what the United States is willing to do militarily to support Israeli strategic objectives, is a genuine and significant challenge whose resolution is not predetermined.</p>
<p>The historical record of the past several years suggests that when Trump's dealmaking instincts collide with Netanyahu's security imperatives, the resulting dynamic is neither the seamless alignment that both governments publicly project nor the open rupture that their critics sometimes predict. It is something more complicated — a relationship of genuine shared interests and genuine strategic disagreement, managed by two leaders who have powerful incentives to appear aligned and powerful independent reasons to pursue different outcomes.</p>
<div class="sources"><strong>Sources:</strong> Reporting by The New York Times, The Wall Street Journal, and Haaretz on Trump-Netanyahu communications (2024-2025); International Atomic Energy Agency reports on Iranian nuclear program (2023-2025); Congressional Research Service, "U.S.-Israel Relations" (2024); Foreign Policy Research Institute analysis of Trump Iran policy; Council on Foreign Relations backgrounder on the Abraham Accords; Middle East Institute analysis of post-October 7 U.S.-Israel strategic coordination.</div>"""

# Apply updates
updates = {
    'new-article-003': {'content': a8_content, 'excerpt': "A documented chronology of Trump's public statements about Epstein — from 'terrific guy' in 2002 to 'not a fan' in 2019 — and the flight logs that complicate his account."},
    'new-article-004': {'content': a9_content, 'excerpt': "Two terms of Trump governance measured against his campaign promises: the lobbyists appointed, the tax cuts delivered, the pardons granted, and the swamp left standing."},
    'new-article-005': {'content': a10_content, 'excerpt': "The formal legal record: two federal jury verdicts finding Trump liable for sexual abuse, the 2016 Jane Doe complaint, and the pattern of 26 public accusers."},
    'new-article-006': {'content': a11_content, 'excerpt': "Bill Gates met Jeffrey Epstein multiple times after his 2008 sex offense conviction. What he sought, what Melinda Gates feared, and what wealth insulates its possessors from."},
    'new-article-007': {'content': a12_content, 'excerpt': "Ghislaine Maxwell built and ran Epstein's trafficking enterprise. Convicted on five counts, serving 20 years — and still not saying what she knows about who else was involved."},
    'new-article-008': {'content': a13_content, 'excerpt': "Inside Little St. James: the architecture of isolation, the surveillance system, the structure on the hill, and what victims testified happened on Epstein's private island."},
    'new-article-009': {'content': a14_content, 'excerpt': "The 2008 Epstein non-prosecution deal was negotiated in secret, concealed from victims, and extended immunity to unnamed co-conspirators. A documented account of how it happened."},
    'new-article-010': {'content': a15_content, 'excerpt': "How Jeffrey Epstein built a system of mutual compromise using surveillance, blackmail leverage, and the willing complicity of banks, prosecutors, and powerful men worldwide."},
    'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d': {'content': a16_content, 'excerpt': "Beneath the Trump-Netanyahu alliance lies a genuine strategic rift over Iran — a divergence over military force, diplomacy, and what the U.S. is willing to risk in the Middle East."},
}

for article in articles:
    aid = article['id']
    if aid in updates:
        article['content'] = updates[aid]['content']
        article['excerpt'] = updates[aid]['excerpt']

# Validate and save
json_str = json.dumps(articles, indent=2, ensure_ascii=False)
test = json.loads(json_str)
print(f'Valid JSON. {len(test)} articles total.')
for a in test:
    wc = len(a['content'].split())
    print(f'  {a["id"][:30]}: {wc} words')

with open('data/articles.json', 'w') as f:
    f.write(json_str)

print('\nWritten to data/articles.json')
