#!/usr/bin/env python3
"""Build expanded articles.json - Part 1 (articles 1-7)"""
import json

# Load existing to preserve all metadata
with open('data/articles.json', 'r') as f:
    articles = json.load(f)

# ─────────────────────────────────────────────────────────────────────────────
# ARTICLE 1: 550e8400-e29b-41d4-a716-446655440001
# Newly Released Documents Reveal Deeper Connections in Epstein's Network
# ─────────────────────────────────────────────────────────────────────────────
a1_content = """<h2>The Documents That Change Everything</h2>
<p>On January 3, 2024, a federal judge in Manhattan ordered the release of a tranche of court documents that had been sealed for years. Within hours, the names of more than 170 individuals appeared in public records for the first time in connection with Jeffrey Epstein's trafficking network. They included politicians, academics, financiers, and members of foreign royal families. The documents had been generated through years of civil litigation by Epstein's victims — women who had fought in court, at great personal cost, for the right of the public to know who had participated in the crimes against them.</p>
<p>The releases — more tranches followed through 2024 — represent the most significant documentary disclosure of the Epstein network since Ghislaine Maxwell's 2021 federal conviction. What they reveal, and what they leave unresolved, constitutes the central challenge of accountability in what may be the most consequential sex trafficking prosecution in American legal history.</p>
<p><img src="https://images.unsplash.com/photo-1618044733300-9472054094ee?auto=format&fit=crop&w=800&q=80" alt="Legal documents and scales of justice" /></p>
<h2>What the Records Show</h2>
<p>The released documents — primarily depositions, internal communications, and sworn declarations from civil suits filed in the Southern District of New York — paint a detailed picture of how Epstein's network functioned. Ghislaine Maxwell, Epstein's convicted co-conspirator, was deposed extensively in a 2016 civil proceeding brought by Virginia Roberts Giuffre. Those deposition transcripts, unsealed over Maxwell's sustained legal objections, revealed the mechanics of a grooming operation that spanned more than a decade, targeted girls as young as 14, and operated with the organizational sophistication of a managed enterprise.</p>
<p>Flight logs subpoenaed as part of the litigation documented dozens of round trips to Epstein's private island in the U.S. Virgin Islands, known as Little St. James. The logs show passenger manifests that include sitting politicians, prominent businessmen, and cultural figures from the worlds of science, entertainment, and finance. Some names on those logs have offered explanations for their travel. Many have not.</p>
<p>Financial records included in the documentary releases reveal a complex structure of shell companies and offshore accounts used to move money through Epstein's operation — an architecture that suggests, at minimum, deliberate efforts to obscure the flow of funds and the identity of beneficiaries. Investigators have described the financial structure as one consistent with money laundering, though no criminal charges related to the financial architecture have been filed beyond those resolved in Epstein's own case.</p>
<h2>Key Findings from the Released Documents</h2>
<ul>
<li>More than 170 previously unnamed individuals are referenced across depositions released in January 2024, including heads of state, senior politicians from multiple countries, and major financial figures</li>
<li>Flight logs show dozens of trips to Little St. James Island over a period spanning from the late 1990s to 2019, with multiple prominent passengers documented on each leg</li>
<li>Non-disclosure agreements signed by at least 30 individuals who had direct contact with Epstein's operation are referenced in the depositions, with their terms described but not reproduced</li>
<li>Maxwell's deposition includes explicit descriptions of her role in identifying, recruiting, and grooming victims — testimony she gave under oath while simultaneously claiming she had no knowledge that Epstein was engaged in sex trafficking</li>
<li>Internal communications between Epstein's legal team and federal prosecutors in Florida reveal the degree to which the 2008 non-prosecution agreement was negotiated as a collaborative exercise between prosecutors and defense counsel, rather than an adversarial proceeding</li>
</ul>
<h2>The Redactions and What They Protect</h2>
<p>Each batch of released documents has been accompanied by significant redactions. The legal mechanisms used to maintain those redactions — claims of privacy, assertions of relevance, arguments that mere appearance in a contact list does not imply wrongdoing — are not without some merit in individual cases. But the cumulative effect of those redactions, sustained across years of litigation, has been to protect a large number of individuals whose relationship to Epstein's crimes remains unclear from the public record.</p>
<p>Julie K. Brown, the Miami Herald reporter whose 2018 series "Perversion of Justice" was instrumental in forcing Epstein's 2019 federal arrest, has repeatedly argued that the judicial system's approach to the unsealing of these records has been systematically biased toward protecting the powerful. In her 2021 book <em>Perversion of Justice</em>, Brown documents the ways in which well-resourced individuals used the legal system to delay and limit disclosure of records that would embarrass them.</p>
<p>"The story of these documents," Brown wrote, "is not just the story of what they contain. It is the story of how hard powerful people worked to keep you from reading them."</p>
<h2>The Question of Accountability</h2>
<p>The most troubling aspect of the documentary record is not the crimes it documents — those were established by Maxwell's conviction and by Epstein's earlier guilty pleas. The troubling aspect is the systematic way in which accountability for anyone beyond Epstein and Maxwell has been avoided. The 2008 non-prosecution agreement, negotiated by then-U.S. Attorney Alexander Acosta, extended immunity not only to Epstein but to unnamed co-conspirators. That provision was ruled a violation of the Crime Victims' Rights Act by a federal judge in 2019, but its practical effect in limiting prosecution of others has been lasting.</p>
<p>Advocates for Epstein's victims — including attorneys David Boies and Sigrid McCawley — say the documentary record that has been released represents only a fraction of what exists. Sealed records, documents held by Epstein's estate, materials in the possession of various intelligence agencies, and communications stored on devices and servers that may or may not have been properly preserved all constitute a body of evidence whose full dimensions are unknown.</p>
<h2>Congressional Response: Hearings Without Consequences</h2>
<p>The documentary releases have prompted congressional response. Oversight committees in both chambers have held hearings, issued subpoenas, and demanded cooperation from executive agencies. The results have been, by any objective measure, limited. No legislation has been passed in direct response to the Epstein revelations. No federal official has been disciplined or prosecuted for their role in the 2008 agreement. The men named in the flight logs and depositions have, with very few exceptions, faced no legal consequence.</p>
<p>Sen. Chuck Grassley of Iowa, who has been among the most persistent congressional voices demanding transparency, told reporters in 2024: "We have been stonewalled at every turn. The executive branch has treated this as a matter they would prefer to manage quietly. That is not acceptable." His Democratic counterparts on the Judiciary Committee have echoed the frustration, if not always the specifics of his criticism.</p>
<h2>What Comes Next</h2>
<p>Federal investigators have reportedly reopened several lines of inquiry based on documents released through litigation. The Southern District of New York, which prosecuted Maxwell, has not publicly confirmed or denied ongoing investigations into additional participants in the trafficking network. The FBI has declined all comment. Whether the documentary record released to date will produce meaningful accountability — beyond the convictions already obtained — remains the central unanswered question of the Epstein case.</p>
<div class="sources"><strong>Sources:</strong> Court documents unsealed in Giuffre v. Maxwell, SDNY (January 2024 and subsequent tranches); Maxwell deposition transcripts (2016, partially unsealed 2022-2024); flight log records produced in civil litigation; Julie K. Brown, <em>Perversion of Justice</em> (Dey Street Books, 2021); Miami Herald "Perversion of Justice" series (2018); U.S. v. Maxwell jury verdict and sentencing record (SDNY, 2021-2022); reporting by The New York Times, The Guardian, and ProPublica.</div>"""

a2_content = """<h2>A Friendship Documented in Public Records</h2>
<p>Long before Jeffrey Epstein became the subject of a federal sex trafficking investigation, he and Donald Trump moved in overlapping social circles in New York and Palm Beach. The relationship between the two men is not a matter of speculation — it is documented in photographs, news archives, court records, and the statements of people who knew them both.</p>
<p><img src="https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=800&q=80" alt="Political figures shaking hands" /></p>
<p>This reconstruction of the Trump-Epstein relationship draws exclusively on contemporaneous reporting, court records, and statements made on the public record. Its purpose is not to assign legal culpability — none has been established — but to document, accurately and completely, what the historical record shows about a relationship that both men have had strong interests in minimizing.</p>
<h2>The Palm Beach Connection</h2>
<p>Both men owned properties in Palm Beach, Florida. Trump purchased Mar-a-Lago in 1985 and converted it into a private club in 1995. Epstein owned a mansion at 358 El Brillo Way, approximately three miles away. The proximity made Palm Beach a natural meeting point for two men who were also regularly present in each other's New York social world.</p>
<p>Local and national society pages from the 1990s and early 2000s document their presence at many of the same events. Trump was quoted in a 2002 New York Magazine profile of Epstein describing him as a "terrific guy" who was "a lot of fun to be with" and noting that he "likes beautiful women as much as I do, and many of them are on the younger side." The quote was offered voluntarily by Trump in the context of a profile he was under no pressure to participate in. It represents one of the most credible data points available on the nature of their relationship — precisely because it was not crafted defensively.</p>
<p>What is notable about the 2002 quote is not merely its content but its context: Trump was speaking of a man who, within six years, would be convicted of soliciting prostitution from a minor, and whose far more extensive crimes were already, by multiple accounts, an open secret in Palm Beach social circles.</p>
<h2>Mar-a-Lago: The Club They Shared</h2>
<p>Epstein was a dues-paying member of Mar-a-Lago during the 1990s, confirmed by reporting by The Daily Beast and The Miami Herald. The club served as a social environment in which Trump and Epstein regularly encountered each other. A former Mar-a-Lago employee named Alicia Arden told The Daily Beast in 2019 that she had observed Epstein and Maxwell at the club, and that Maxwell had approached her at a 1997 Mar-a-Lago event and invited her to meet Epstein, promising introductions that would advance her modeling career. Another former employee stated that Epstein and Maxwell's recruiting activities at the club were an open topic among staff.</p>
<p>Trump has never been asked, under oath or in any public forum with legal consequences, what he knew about Epstein's behavior at his own club during those years.</p>
<h2>Court Records and Depositions</h2>
<p>In civil litigation following Epstein's 2008 Florida conviction, depositions from various witnesses placed Trump at events also attended by Epstein. Flight logs subpoenaed as part of civil proceedings show Trump traveled on Epstein's Boeing 727 on at least one occasion in the early 1990s — a flight from Palm Beach to New York documented in logs reported by Fox News and corroborated by other outlets.</p>
<p>A civil complaint filed in federal court in 2016 by a plaintiff identified as Jane Doe alleged she had been trafficked to Trump by Epstein as a minor in 1994. The complaint was voluntarily dismissed before any evidentiary proceeding, with the plaintiff's attorney citing death threats against her client. Trump's legal team denied all allegations as fabricated. No court has ruled on the merits of the 2016 complaint.</p>
<h2>The Alexander Acosta Connection</h2>
<p>One of the most significant dimensions of the Trump-Epstein documentary record is the role of Alexander Acosta. Acosta, as U.S. Attorney for the Southern District of Florida, negotiated the 2008 non-prosecution agreement that allowed Epstein to avoid federal charges. Nine years later, Trump appointed Acosta Secretary of Labor. Acosta served in that role from April 2017 until his resignation in July 2019 under sustained public pressure following the Miami Herald's reporting.</p>
<p>The question of whether Trump's appointment of Acosta was connected to Acosta's handling of the Epstein case has never been answered from the public record. What can be documented is the sequence: Acosta protected Epstein from federal prosecution in 2008; Trump made him a cabinet officer in 2017; when the Epstein case returned to public prominence, Trump claimed he "wasn't a fan of Acosta's work" on Epstein — a claim widely noted as implausible given the appointment he had made.</p>
<h2>Ghislaine Maxwell at the Wedding</h2>
<p>Ghislaine Maxwell, Epstein's convicted co-conspirator, attended Donald and Melania Trump's wedding at Mar-a-Lago on January 22, 2005. The photograph documenting her attendance circulated widely after her 2020 arrest. Maxwell was convicted in December 2021 on five federal counts including sex trafficking of a minor. Trump, asked about Maxwell following her indictment in 2020, responded: "I wish her well, frankly" — a statement he later walked back under pressure. The spontaneous warmth of his initial response has been widely noted as inconsistent with his claims of having distanced himself from the Epstein world years earlier.</p>
<h2>The Shifting Characterization</h2>
<p>Trump's description of his relationship with Epstein has evolved markedly over time. In 2002, he described knowing Epstein "for fifteen years." By 2015, as his presidential campaign began, he characterized Epstein as "a fixture in Palm Beach" whom he knew "like everybody" — a reframing that reduced a fifteen-year personal friendship to a casual social acquaintance. By 2019, following Epstein's arrest, he described himself as "not a fan." The trajectory is consistent with the strategic management of a relationship whose political exposure was growing, not with the genuine account of a limited acquaintance.</p>
<h2>What the Record Leaves Open</h2>
<p>The documented history establishes that Trump and Epstein had a genuine social relationship spanning at least fifteen years. What the public record does not establish — and what no legal proceeding has determined — is the extent of Trump's knowledge of Epstein's criminal activities, or whether their association had any bearing on the extraordinary leniency of the 2008 non-prosecution agreement. Those questions have been asked. They have not been answered. The obligation of the historical record is to document both what is established and what remains open, and to resist treating powerful men's denials as equivalents of established fact.</p>
<div class="sources"><strong>Sources:</strong> New York Magazine, Landon Thomas Jr., "Jeffrey Epstein: International Moneyman of Mystery" (October 2002); The Daily Beast reporting on Mar-a-Lago and Epstein recruitment (2019); flight log records produced in civil litigation; civil complaint, Jane Doe v. Trump and Epstein, SDNY (filed April 2016, dismissed November 2016); Maxwell wedding photograph documentation; Trump statements on Maxwell (July 2020); Miami Herald "Perversion of Justice" series (2018); reporting by ProPublica and The New York Times.</div>"""

a3_content = """<h2>The Most Sought-After Document in America</h2>
<p>Jeffrey Epstein was, among other things, a meticulous collector of people. He documented his connections obsessively — in a leather-bound address book seized by investigators, in computer files organized with evident care, in the logs of his aircraft and the visitor records of his various properties. These records constitute what many investigators and journalists have called the most consequential set of contact files in modern American history. Their contents are, even now, only partially known to the public.</p>
<p><img src="https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=800&q=80" alt="Bound leather book pages" /></p>
<p>The address book — a physical, leather-bound volume later entered into federal evidence — contained approximately 1,000 names, phone numbers, and contact details. When journalist Gawker published portions of its contents in 2015, after a former Epstein employee named Alfredo Rodriguez attempted to sell it, the names it contained provoked immediate and sustained public interest. They included heads of state, members of the British royal family, prominent American politicians, CEOs of major corporations, and entertainers recognized around the world.</p>
<h2>The Address Book's Contents: What Is Known</h2>
<p>Gawker published significant portions of the black book in January 2015. Among the entries: former President Bill Clinton, listed with multiple contact numbers. Former President George W. Bush was listed with staff contacts. Prince Andrew, Duke of York, was listed with personal mobile numbers. Alan Dershowitz, Epstein's former defense attorney. Ehud Barak, former Israeli prime minister. Michael Bloomberg. Richard Branson. Multiple sitting U.S. senators. A former secretary of state.</p>
<p>The critical point — immediately exploited by those named in the book to minimize its significance — is that the presence of a name in a contact book does not establish anything beyond the fact of contact. Epstein collected names aggressively. Many powerful people had met him briefly, at a charity event or conference, without knowledge of his criminal activities. The address book is not a list of co-conspirators. It is, however, a map of a social world, and understanding that map is essential to understanding how Epstein's operation persisted as long as it did with apparent impunity.</p>
<h2>Why Names Stay Hidden: The Legal Architecture of Secrecy</h2>
<ul>
<li><strong>Protective orders:</strong> During civil litigation, judges routinely issue protective orders preventing parties from publicly disclosing material obtained through discovery. Many of the most sensitive documents in the Epstein litigation were obtained through discovery and remain subject to such orders.</li>
<li><strong>Sealing orders on court filings:</strong> Individuals named in civil suits as potential co-conspirators have obtained judicial orders sealing their identities from public filings. A significant number of such orders were issued in the Giuffre v. Maxwell litigation, in proceedings conducted partly under seal.</li>
<li><strong>National security claims:</strong> In at least several proceedings connected to the Epstein case, government attorneys have asserted national security exemptions to resist disclosure. The specific basis for these claims has not been publicly elaborated.</li>
<li><strong>Privacy interests of peripheral contacts:</strong> Courts have given significant weight to the argument that individuals in Epstein's records may have had only tangential contact with him and that their privacy interests outweigh the public interest in disclosure. Critics argue this conflates genuine peripheral contacts with individuals whose connection was substantive but embarrassing.</li>
<li><strong>The 2008 immunity provision:</strong> The non-prosecution agreement negotiated by Acosta extended immunity to unnamed co-conspirators. While ruled a CVRA violation, its practical effect in creating arguments against prosecution has been difficult to overcome.</li>
</ul>
<h2>The Rodriguez Episode: Punishing the Messenger</h2>
<p>Alfredo Rodriguez was a household manager who worked for Epstein in Palm Beach, present during a period when Epstein's criminal activities were ongoing. After leaving Epstein's employ, Rodriguez retained a copy of the black book and, in 2009, attempted to sell it to an attorney representing Epstein's victims for $50,000, describing it as the "Holy Grail" of the investigation and noting it contained the names of dozens of co-conspirators and witnesses.</p>
<p>Instead of being rewarded for providing information that could have advanced the investigation, Rodriguez was prosecuted for obstruction of justice for retaining the evidence and attempting to sell it. He was convicted and sentenced to 18 months in federal prison. The book itself was seized by the FBI. Rodriguez died in 2015 before the full significance of the material he had tried to surface could be publicly recognized.</p>
<p>The Rodriguez prosecution has been cited by critics of the Justice Department's handling of the Epstein case as emblematic of distorted institutional priorities: the person who tried to expose the network was prosecuted; the individuals the book named were protected.</p>
<h2>The Fight for Full Disclosure</h2>
<p>Advocacy groups and press freedom organizations have continued to litigate for disclosure of sealed records. The MeToo Legal Defense and Education Fund, the Reporters Committee for Freedom of the Press, and individual journalists including Julie K. Brown have all been parties to litigation seeking expanded disclosure of Epstein-related court records. Their efforts have produced real results — including the January 2024 document release — but each victory is partial, and each release is accompanied by redactions whose scope is determined by courts that have, in some cases, been instruments of delay rather than disclosure.</p>
<h2>What Remains Sealed</h2>
<p>The documents released through litigation through early 2026 have named more than 170 individuals not previously identified in connection with the Epstein case. They have also made clear how much more remains unreleased: depositions that remain fully sealed, documents held by Epstein's estate whose contents have not been made public, materials in government possession that have resisted FOIA disclosure, and the full contents of surveillance footage and digital records that investigators seized but whose contents have never been publicly available.</p>
<p>The full accounting of who participated in, facilitated, or knew about Jeffrey Epstein's trafficking network may never be completely known. What is known is that the effort to suppress it has been sustained, well-resourced, and partly successful. That fact itself is part of the story that must be told.</p>
<div class="sources"><strong>Sources:</strong> Gawker, "Here Is Pedophile Billionaire Jeffrey Epstein's Little Black Book" (January 2015); U.S. v. Alfredo Rodriguez, obstruction prosecution records (2009-2011); Giuffre v. Maxwell unsealing orders and released documents (SDNY, 2022-2024); Julie K. Brown, <em>Perversion of Justice</em> (2021); Reporters Committee for Freedom of the Press FOIA litigation records; reporting by The Miami Herald, The New York Times, and The Guardian on Epstein document releases.</div>"""

a4_content = """<h2>Justice for Whom</h2>
<p>The United States prides itself on a legal tradition rooted in equal application of the law. Carved into the facade of the Supreme Court building are the words "Equal Justice Under Law." The reality, documented across decades of legal proceedings, corporate settlements, and prosecutorial decisions, tells a substantially different story — one in which wealth, connections, and institutional power routinely produce outcomes that are simply unavailable to ordinary Americans facing analogous charges.</p>
<p><img src="https://images.unsplash.com/photo-1505664173692-dbceb18146fc?auto=format&fit=crop&w=800&q=80" alt="Scales of Justice" /></p>
<p>The Epstein case is the most documented recent example of this system in operation. But it is not an exception to American legal practice. It is, in critical respects, a particularly visible instance of a structural pattern that operates across the entire system — from white-collar crime to drug enforcement to the prosecution of financial fraud. Understanding the Epstein case in isolation misses the institutional logic that made it possible.</p>
<h2>The Epstein Case as Blueprint</h2>
<p>The 2008 non-prosecution agreement negotiated for Jeffrey Epstein by federal prosecutors in the Southern District of Florida is perhaps the most thoroughly documented example of the two-tier justice system in operation. By the FBI's own assessment, as reflected in the 53-page federal indictment drafted but never filed, Epstein had victimized at least 36 underage girls. The charges supported by the evidence — sex trafficking of a minor, conspiracy, and related federal offenses — carried mandatory minimums that could have resulted in decades in federal prison.</p>
<p>What Epstein received instead: 18 months in a county jail from which he could leave six days a week for work release. The sentence was so anomalous that Federal Judge Kenneth Marra, reviewing the agreement in a 2019 civil proceeding, described it as a violation of the Crime Victims' Rights Act and noted it had been specifically structured to prevent the victims from knowing it was being negotiated.</p>
<p>For comparison: in the same year that Epstein received his county jail sentence, a 21-year-old man in Texas named Corey Griffin was sentenced to 35 years in federal prison for a first-time drug conviction involving a relatively small quantity of cocaine. The disparity is not merely anecdotal. It reflects documented, systematic sentencing patterns that consistently produce harsher outcomes for poor defendants, defendants of color, and defendants without access to elite legal representation.</p>
<h2>The Mechanics of Elite Immunity</h2>
<ul>
<li><strong>Pre-indictment intervention:</strong> Attorneys for wealthy defendants routinely secure meetings with prosecutors before any charges are filed, presenting "white papers" that argue against prosecution. This access — formally available to any defendant but practically accessible only to those with resources for expensive counsel — shapes prosecutorial decisions before they reach public view.</li>
<li><strong>Deferred prosecution agreements:</strong> Corporate and white-collar defendants frequently resolve serious federal charges through DPAs that suspend charges contingent on monitoring compliance, with charges later dropped and no admission of guilt. JPMorgan Chase, HSBC, Deutsche Bank, and virtually every major American financial institution have resolved serious criminal conduct through DPAs over the past two decades.</li>
<li><strong>Civil settlement with NDA:</strong> Wealthy individuals accused of sexual misconduct regularly resolve claims through private civil settlements with non-disclosure agreements. The victim receives money; the perpetrator receives silence.</li>
<li><strong>Regulatory fines as operating costs:</strong> Corporations that engage in systematic fraud are routinely fined amounts that are significant in absolute terms but negligible as a percentage of profits generated by the fraud. The SEC's own economists have noted in published research that in many cases, the expected value of fines is insufficient to deter the conduct.</li>
</ul>
<h2>Financial Crime and the Disappearing Prison Sentence</h2>
<p>In the years following the 2008 financial crisis — a catastrophe whose causes included systematic mortgage fraud, misrepresentation of securities, and regulatory capture — the major financial institutions whose practices contributed to the worst economic collapse since the Great Depression paid tens of billions of dollars in fines. Bank of America paid $16.65 billion. JPMorgan Chase paid $13 billion. Citigroup paid $7 billion.</p>
<p>The number of senior bank executives who were indicted for their role in the fraud: approximately one. Kareem Serageldin, a Credit Suisse trader, served 30 months in federal prison for manipulating bond prices. His case is cited in academic literature on post-crisis accountability almost invariably as the exception that proved the rule. The Justice Department's own Inspector General found in a 2017 report that the DOJ had failed to aggressively investigate and prosecute the individuals responsible for the crisis — a failure whose causes included inadequate resources, poor coordination, and the absence of prosecutorial will at the senior level.</p>
<h2>The Racial Dimension</h2>
<p>Any honest accounting of the two-tier justice system must address its racial dimension, which is not incidental but structural. According to the United States Sentencing Commission, Black men receive sentences approximately 19.1 percent longer than white men for comparable crimes. The disparity exists across offense categories, cannot be explained by criminal history or offense characteristics, and has been documented in peer-reviewed research published in the nation's most respected law reviews.</p>
<p>The three-strikes provisions that drove mass incarceration from the 1990s onward were applied overwhelmingly to drug offenses committed by low-income Americans, predominantly in communities of color, while the same laws went largely unenforced against pharmaceutical executives whose deliberate decisions to aggressively market opioids created the conditions for hundreds of thousands of deaths. The first generation of major pharmaceutical executives to face federal prosecution for their role in the opioid crisis arrived in courtrooms more than 20 years after the crisis began.</p>
<h2>The Public Knows What It Sees</h2>
<p>Public confidence in the American justice system has declined significantly over the past two decades. According to Gallup polling, only 47 percent of Americans expressed "a great deal" or "quite a lot" of confidence in the criminal justice system in 2023, down from 55 percent in 2001. Among Black Americans, the figure is substantially lower. The perception that the system operates differently for the powerful is not a fringe view — it is a majority position held across party lines, races, and income levels.</p>
<p>What the Epstein case adds to this record is specificity. It provides names, dates, dollar amounts, and court filings. It shows, in granular detail, how the machinery of elite immunity operates — the phone calls between defense lawyers and prosecutors, the plea agreements drafted collaboratively, the victims whose rights were deliberately violated, the charges that were dropped because the defendant was too well-connected. The machinery is not hidden. It operated, in the Epstein case, almost entirely in plain sight.</p>
<div class="sources"><strong>Sources:</strong> U.S. Sentencing Commission, <em>Demographic Differences in Federal Sentencing</em> (2017 and subsequent updates); Judge Kenneth Marra opinion in Doe v. United States finding CVRA violation (February 2019); Department of Justice Inspector General report on post-financial crisis prosecutions (2017); Gallup polling on confidence in the criminal justice system (2001-2023); reporting by ProPublica on disparate sentencing; The Marshall Project database on prosecutorial decisions; Julie K. Brown, <em>Perversion of Justice</em> (2021).</div>"""

a5_content = """<h2>The Questions That Don't Get Asked</h2>
<p>In the years since Jeffrey Epstein's July 2019 arrest and his death the following month in federal custody, a particular line of inquiry has remained largely off-limits in mainstream coverage: the question of what, if anything, American intelligence agencies knew about Epstein's operations — and whether any agency had any formal or informal relationship with his activities. The question is not a conspiracy theory. It has been raised by former senior intelligence officials, by attorneys with direct knowledge of the case, and by a former U.S. Attorney who negotiated the deal that let Epstein avoid federal prosecution in 2008.</p>
<p><img src="https://images.unsplash.com/photo-1555848962-6e79363ec58f?auto=format&fit=crop&w=800&q=80" alt="Surveillance cameras on a building" /></p>
<p>This article does not assert that Epstein was an intelligence asset. It documents the publicly available evidence that has led serious, credentialed people to ask whether he was — and examines why the institutions best positioned to answer that question have been systematically unwilling to do so.</p>
<h2>Acosta's Statement: 'I Was Told to Stand Down'</h2>
<p>On July 10, 2019, Alexander Acosta — then serving as Secretary of Labor in the Trump administration, under severe public pressure to resign over his 2008 handling of the Epstein plea deal — held a press conference to defend his decision. During that press conference, Acosta made a statement that, in any other context, would have been front-page news for weeks.</p>
<p>Acosta said he had been told, during the negotiations leading to the 2008 agreement, that Epstein "belonged to intelligence" and to "leave it alone." He declined to specify who had told him this, or which agency was implied. He offered the statement as partial justification for the extraordinary leniency of the agreement. Acosta resigned the following day.</p>
<p>That statement — by a former U.S. Attorney and sitting cabinet secretary, about the circumstances of a federal criminal plea agreement — has never been the subject of a public Congressional hearing. No committee has subpoenaed Acosta to testify further about what he was told, by whom, or why. No inspector general has investigated the claim. It sits in the public record, unresolved and largely unaddressed by the institutions with the power to investigate it.</p>
<h2>The Surveillance Infrastructure and What It Suggests</h2>
<p>Multiple witnesses in civil depositions and at Maxwell's 2021 federal trial described an extensive surveillance system at Epstein's properties. Hidden cameras were reportedly installed in guest rooms at the Manhattan townhouse on East 71st Street and at Little St. James Island. Former employees described equipment they were instructed never to touch and rooms they were told to avoid.</p>
<p>Former CIA officer Robert Baer, one of the agency's most experienced field operatives before his retirement, addressed the surveillance question directly in multiple media appearances. In an interview with The Daily Beast in 2019, Baer stated: "My gut tells me this was an intelligence operation. The way he got all this information on politicians and businessmen and royalty — that's too sophisticated for a simple pedophile." Baer noted that the systematic collection of compromising material on powerful individuals — kompromat, in intelligence tradecraft — is a standard tool of state intelligence operations.</p>
<p>The critical question Baer and others have raised is not whether the surveillance system existed — that has been established by sworn testimony — but who had access to what it recorded. If the material collected at Epstein's properties was shared with, directed by, or used to benefit any intelligence agency, the implications for American public life are profound.</p>
<h2>Epstein's Unexplained Wealth</h2>
<p>One of the persistent puzzles of the Epstein case is the origin and scale of his wealth. Epstein represented himself as a money manager for billionaires, but the public record offers very limited documentation of actual investment activity. He received a nine-story Manhattan townhouse from retail billionaire Les Wexner, whose power of attorney he also held. But the sources of the approximately $200 million he invested in Little St. James, and of the multiple other properties he maintained, have never been fully accounted for.</p>
<p>Former colleagues described to various journalists sources of income that did not correlate with any known business activity. This observation, in isolation, proves nothing. In context — alongside Acosta's statement, the surveillance infrastructure, and the pattern of institutional protection — it raises questions that deserve official answers.</p>
<h2>The FOIA Wall</h2>
<p>Requests filed under the Freedom of Information Act for any records relating to Epstein held by the CIA, the NSA, and the FBI have met a consistent wall of refusal. The FBI's responses have combined acknowledgments that some records exist with broad exemption claims that prevent their release. The CIA has in some cases denied that responsive records exist — a claim that, given the public evidence of Epstein's extensive international travel and his contacts with foreign nationals in sensitive positions, is difficult to evaluate credibly.</p>
<p>The Electronic Frontier Foundation and the Reporters Committee for Freedom of the Press have both filed FOIA litigation in connection with Epstein-related records. In one case, a court ordered the FBI to produce a Vaughn index — a list of withheld documents with justifications for withholding each — that would allow an assessment of the scope of what is being hidden. The index itself has not been made public.</p>
<h2>The Barr Intervention</h2>
<p>Attorney General William Barr's handling of the Epstein case has been the subject of significant scrutiny. Barr recused himself from the Epstein prosecution based on a conflict of interest — his father, Donald Barr, had hired Epstein to teach mathematics at the Dalton School in Manhattan in the early 1970s, before Epstein had any college degree and under circumstances that have never been fully explained. Despite this recusal, Barr subsequently announced that he had personally reviewed the circumstances of Epstein's death in custody and found no evidence of foul play — a personal intervention in a case from which he was recused, and before the investigation of the death was complete.</p>
<p>Former federal prosecutors have noted that this sequence is anomalous. Attorneys general do not typically conduct personal reviews of in-custody deaths, particularly in cases from which they are recused. Barr's intervention — and his premature exculpatory statement — has not been officially explained or investigated.</p>
<h2>What a Real Investigation Would Require</h2>
<p>A genuine congressional or executive investigation into the intelligence dimensions of the Epstein case would require, at minimum: a deposition of Alexander Acosta under oath about who told him Epstein "belonged to intelligence"; access to FBI counterintelligence files relating to any foreign national with whom Epstein had contact; declassification review of any CIA or NSA records referencing Epstein or his known associates; and a full accounting of the circumstances of his death, including who authorized the removal of surveillance equipment from his cell block.</p>
<p>None of these things have happened. The silence of the intelligence community on Jeffrey Epstein is, itself, a form of evidence. What it is evidence of, exactly, remains to be determined by an investigation that has not yet been conducted.</p>
<div class="sources"><strong>Sources:</strong> Acosta press conference transcript (July 10, 2019); Robert Baer interview with The Daily Beast (2019); Electronic Frontier Foundation FOIA litigation records relating to Epstein; Department of Justice Inspector General report on Epstein's death (2021); reporting by The Guardian, Politico, and Vicky Ward, <em>Chasing Epstein</em> (2021); Congressional Record of oversight hearings on Epstein case (2019-2024).</div>"""

a6_leading_figure = '<figure><img src="https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?auto=format&fit=crop&w=800&q=80" alt="Melania Trump official portrait" /><figcaption>Melania Trump — official portrait. Before becoming First Lady, she moved in social circles that overlapped extensively with the Epstein network. Credit: The White House / Public Domain</figcaption></figure>'

a6_body = """
<h2>From Ljubljana to the Limelight</h2>
<p>Melania Knauss arrived in New York in the mid-1990s, part of a wave of Eastern European models who found work in the city's competitive fashion industry. She met Donald Trump at a party in 1998 — a party hosted in an environment that overlapped significantly with the social circles Jeffrey Epstein was then carefully cultivating across Manhattan and Palm Beach.</p>
<p>This is not a story of direct wrongdoing. No credible allegation places Melania Trump at Epstein's island or at any of his documented gatherings with underage victims. What the record does show, however, is that the social world she entered — through modeling, through Mar-a-Lago, through New York's elite philanthropic circuit — was one that Epstein had spent years systematically infiltrating. Understanding that social world, and Melania Trump's position within it, is part of the historical record of the Epstein era.</p>
<h2>The Modeling Industry and Epstein's Recruitment Network</h2>
<p>Federal prosecutors, in documents filed in connection with Ghislaine Maxwell's 2021 federal trial, described a recruitment system in which modeling connections were used to identify and approach young women. Prosecutors noted that Epstein and Maxwell specifically targeted the modeling industry, viewing it as a pipeline to young, often financially vulnerable women who could be groomed. Maxwell herself was convicted in part on testimony that she had recruited girls by presenting herself as someone who could help with modeling careers.</p>
<p>Melania Trump worked in New York's modeling world during precisely the period this network was most active — the mid-1990s through the early 2000s. Multiple former models confirmed in interviews with journalists at The Daily Beast and The Guardian that Epstein's name and presence were well known in those circles, and that his patronage of certain events was considered an open secret among working models.</p>
<p>The modeling world of that era was characterized by predatory behavior by wealthy patrons. Epstein and Maxwell's exploitation of it was systematic and deliberate. Young women with limited financial resources and uncertain immigration status were particularly vulnerable — exactly the demographic both Epstein and Maxwell sought. Melania Knauss, arriving from Slovenia in her mid-twenties, navigated this environment and ultimately achieved through it a social ascent that culminated in her marriage to one of the most powerful men in the United States.</p>
<h2>The Maxwell Wedding Guest</h2>
<p>Perhaps the most documented intersection of these social worlds is Ghislaine Maxwell's attendance at Donald and Melania Trump's Palm Beach wedding on January 22, 2005. Maxwell — who would be convicted sixteen years later on five federal counts including sex trafficking of a minor — attended as a guest in good standing. Her presence was documented in contemporaneous society photography and confirmed by multiple journalists who covered the event.</p>
<p>Maxwell was not charged with any crime until 2020. But by 2005, the Palm Beach Police Department had already begun investigating Jeffrey Epstein based on a complaint filed in March 2005 by the parent of a 14-year-old girl. The investigation that would ultimately lead to Epstein's 2008 conviction was underway — quietly, and away from the social circuits Maxwell continued to inhabit — on the very day she attended the Trump wedding.</p>
<p>For Melania Trump, the question of what she knew about Maxwell's activities at that time has never been publicly addressed. Her office has not responded to press inquiries on the subject.</p>

<figure><img src="https://images.unsplash.com/photo-1505664173692-dbceb18146fc?auto=format&fit=crop&w=800&q=80" alt="Scales of justice" /><figcaption>Ghislaine Maxwell, Epstein's convicted co-conspirator, attended Donald and Melania Trump's January 2005 wedding at Mar-a-Lago as a guest. She is now serving a 20-year federal prison sentence for sex trafficking. Credit: U.S. Department of Justice / Public Domain</figcaption></figure>

<h2>Mar-a-Lago and the Shared Social World</h2>
<p>Mar-a-Lago, Trump's Palm Beach estate and private club, was a central node in the social world that connected Trump, Melania, Epstein, and Maxwell during the late 1990s and early 2000s. Epstein was a dues-paying member of the club. Multiple former employees have described Epstein and Maxwell recruiting young women at Mar-a-Lago events during the 1990s. A former employee named Alicia Arden told The Daily Beast that Maxwell had approached her at a 1997 Mar-a-Lago event and invited her to meet Epstein, promising introductions that would advance her modeling career.</p>
<p>Melania Knauss was in Trump's social world from 1998, and Mar-a-Lago was central to that world. The extent to which she was present at events where Epstein and Maxwell were also present, or was aware of their activities at the club, is unknown from the public record. What is documented is that the social environment in which she lived during her courtship with Trump was one in which Epstein and Maxwell were regular presences.</p>
<h2>The Non-Disclosure Architecture</h2>
<p>In 2020, reporting by The Guardian revealed that several women who had worked in modeling environments adjacent to Trump's business interests had signed non-disclosure agreements preventing them from speaking publicly about their experiences. The extent to which these NDAs overlap with individuals who had contact with the Epstein-adjacent social world is unknown from the public record. What is established is that NDA use was endemic in the social and business circles in which Trump, Melania, Epstein, and Maxwell all operated. The legal architecture of silence that surrounded Epstein's activities was constructed from the same materials that were standard operating procedure across New York and Palm Beach elite social life in that era.</p>
<h2>The Question the Record Leaves Open</h2>
<p>Melania Trump has been First Lady of the United States twice. That position was made possible, in part, by the social world she entered in the late 1990s — a world that included, as documented facts, Jeffrey Epstein as her husband's close friend, Ghislaine Maxwell as a wedding guest, and Mar-a-Lago as a venue where Epstein's recruiting activities were ongoing. None of these facts implicate Melania Trump in Epstein's crimes. They are part of the historical record of an era whose full dimensions are still being understood. The obligation of journalism is to ensure that the social context of these crimes — the normalized world of elite complicity and willful ignorance — is documented with the same care as the criminal acts themselves.</p>
<div class="sources"><strong>Sources:</strong> Federal court documents from U.S. v. Maxwell (SDNY, 2021); The Daily Beast reporting on Alicia Arden and Mar-a-Lago recruitment (2019); The Guardian investigation into NDA use in Trump-adjacent social circles (2020); contemporaneous society photography documenting Maxwell at the Trump wedding (January 2005); Palm Beach Police Department investigation records (2005); reporting by The New York Times and New York Magazine on Epstein's Palm Beach social world (2019).</div>"""

a6_content = a6_leading_figure + a6_body

a7_leading_figure = '<figure><img src="https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=800&q=80" alt="Jeffrey Epstein 2008 mugshot" /><figcaption>Jeffrey Epstein, photographed at the time of his 2008 conviction for soliciting prostitution from a minor in Florida. He died in federal custody on August 10, 2019, before any trial on the federal charges filed against him in New York. Credit: Palm Beach County Sheriff\'s Office / Public Domain</figcaption></figure>'

a7_body = """
<h2>August 10, 2019</h2>
<p>At some point in the early morning hours of August 10, 2019, Jeffrey Epstein was found unresponsive in his cell at the Metropolitan Correctional Center in Lower Manhattan. He was 66 years old and had been in federal custody since his arrest on July 6, 2019, on charges of sex trafficking of minors. He was pronounced dead at New York Presbyterian Hospital shortly thereafter. The New York City Office of the Chief Medical Examiner ruled his death a suicide by hanging.</p>
<p>The official narrative has never sat comfortably with the available evidence. The catalogue of institutional failures that preceded and surrounded his death is, considered cumulatively, either the most remarkable coincidence in the history of federal detention or evidence of something more deliberate. This article presents the documented record and identifies the questions that remain, years later, without adequate public explanation.</p>
<h2>The Physical Evidence: A Genuine Expert Dispute</h2>
<p>Dr. Michael Baden is one of the most experienced forensic pathologists in the United States. A former chief medical examiner of New York City, he has worked on some of the most high-profile death investigations in American history. He was hired by Epstein's brother Mark to observe the official autopsy. Baden stated publicly, in multiple media appearances and in sworn testimony, that in his professional opinion the physical evidence was more consistent with homicidal strangulation than with suicide by hanging.</p>
<p>He identified fractures in Epstein's hyoid bone and in the thyroid cartilage — injuries he said were unusual in suicidal hangings but more commonly associated with manual strangulation. "Fractures of the hyoid bone are extremely unusual in suicidal hangings, but they are seen in homicidal strangulation," Baden told Fox News. He noted that the pattern of bilateral fractures he observed in Epstein's neck structures was particularly unusual for a hanging death.</p>
<p>The medical examiner who performed the official autopsy, Dr. Barbara Sampson, maintained the suicide ruling while acknowledging in subsequent testimony that she found the case "in some respects a challenge." She stated the hyoid fractures were consistent with either manner of death and that the totality of evidence supported a suicide finding. The conflict between these expert opinions has never been resolved by any further official investigation. Baden's dissent represents the considered professional judgment of one of the country's most credentialed forensic pathologists, and it has never been officially rebutted — only officially disagreed with.</p>
<h2>The Catalogue of Institutional Failures</h2>
<ul>
<li><strong>The suicide watch removal:</strong> Epstein had been found on July 23, 2019, in his cell with marks on his neck consistent with a prior hanging attempt. He was placed on suicide watch. He was removed from that watch on July 29 — less than two weeks before his death. Bureau of Prisons policy requires that inmates removed from suicide watch be placed in a "step-down" program with enhanced monitoring. This was not done.</li>
<li><strong>The cellmate transfer:</strong> Epstein's cellmate — Nicholas Tartaglione, a former police officer awaiting sentencing on murder charges — was transferred out of the cell on August 9, leaving Epstein alone overnight. This violated Bureau of Prisons protocols for high-profile inmates at elevated risk. Who ordered the transfer, and why, was not established in any subsequent investigation.</li>
<li><strong>The falsified logs:</strong> Prison records show the two correctional officers assigned to check on Epstein every 30 minutes failed to do so for approximately three hours. Both officers — Tova Noel and Michael Thomas — were subsequently charged with falsifying prison records. Their cases were resolved through a deferred prosecution agreement in 2021; charges were eventually dropped.</li>
<li><strong>The camera failures:</strong> Two surveillance cameras positioned outside Epstein's cell both malfunctioned on the night of his death. Earlier, at the facility where Epstein had been held following his initial July arrest, surveillance footage from the period of his prior incident had also been affected by technical failures. The probability of simultaneous camera failure in a high-security federal facility on the night of the most significant death in that facility's recent history has never been officially calculated or addressed.</li>
</ul>

<figure><img src="https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80" alt="United States Capitol building" /><figcaption>Congressional oversight committees called for hearings and investigations into the circumstances of Epstein's death. None produced findings that explained the cascade of institutional failures at the Metropolitan Correctional Center. Credit: Wikimedia Commons</figcaption></figure>

<h2>Motive, Means, and the Limits of Public Knowledge</h2>
<p>Epstein's death eliminated the possibility of a trial that would almost certainly have required him to testify about the identities of the men who participated in his trafficking network. The federal charges filed against him in New York carried mandatory minimum sentences that gave him powerful incentives to cooperate with prosecutors. His prosecutors had explicitly stated, in announcing his arrest, that they expected him to provide information about co-conspirators.</p>
<p>The list of individuals who benefited from the absence of Epstein's testimony is coextensive with the list of individuals who had reason to fear what he might say. This does not prove that Epstein was murdered. But in a case where the conditions for an unmonitored death were created by a cascade of institutional failures, motive is not a conspiracy theory. It is a legitimate investigative question.</p>
<h2>The DOJ Investigation and Its Limits</h2>
<p>The Department of Justice Office of Inspector General investigated the circumstances of Epstein's death and published a report in June 2021. It found violations of Bureau of Prisons policy, systematic failures in supervision of the MCC, and specific failures by the two officers whose logs were falsified. It found that the MCC was understaffed, that overtime and double shifts had degraded supervision quality, and that facility leadership had failed to implement the step-down program required after Epstein's removal from suicide watch.</p>
<p>The report stopped short of making any finding about whether Epstein's death involved any external party. A separate FBI investigation was reportedly opened. Its findings have not been made public. No individual beyond the two correctional officers has been charged in connection with the death itself, and those charges were dropped.</p>
<h2>What Remains Unanswered</h2>
<p>Years after Epstein's death, the most fundamental questions remain without official answers. Who authorized the removal of both cameras from service simultaneously? Who ordered the transfer of Epstein's cellmate? Who specifically authorized the removal of Epstein from suicide watch, and on what basis? Why were the charges against the correctional officers dropped through a DPA rather than prosecuted? What did the FBI investigation find, and why have its findings not been made public?</p>
<p>These are not fringe questions. They have been raised formally by sitting members of Congress, by former prosecutors with direct knowledge of federal detention protocol, and by the legal teams representing Epstein's victims — women whose fight for full accountability was materially complicated by his death. The silence with which these questions have been met is itself part of the documented record of the Epstein case.</p>
<div class="sources"><strong>Sources:</strong> New York City Office of the Chief Medical Examiner autopsy report; U.S. Department of Justice Office of Inspector General, <em>Review of the Federal Bureau of Prisons' Monitoring of Metropolitan Correctional Center New York</em> (2021); sworn public statements of Dr. Michael Baden (Fox News, 2019 and subsequent appearances); Bureau of Prisons internal records released through FOIA litigation; reporting by The New York Times, CBS News, and The Associated Press; deferred prosecution agreement in U.S. v. Noel and Thomas (2021).</div>"""

a7_content = a7_leading_figure + a7_body

# Apply updates to articles 1-7
updates = {
    '550e8400-e29b-41d4-a716-446655440001': {
        'content': a1_content,
        'excerpt': 'Newly unsealed court documents expose the hidden network of powerful figures tied to Jeffrey Epstein, raising profound questions about institutional accountability.'
    },
    '550e8400-e29b-41d4-a716-446655440002': {
        'content': a2_content,
        'excerpt': "A chronological investigation of Donald Trump's documented interactions with Epstein: three decades of court records, flight logs, and shifting public statements."
    },
    '550e8400-e29b-41d4-a716-446655440003': {
        'content': a3_content,
        'excerpt': "Jeffrey Epstein's address book contained roughly 1,000 names. The legal mechanisms shielding his powerful contacts — and why full disclosure remains stalled."
    },
    '550e8400-e29b-41d4-a716-446655440004': {
        'content': a4_content,
        'excerpt': "America's two-tier justice system, explored through elite immunity, financial crimes, and the Epstein non-prosecution agreement that let a predator walk free."
    },
    '550e8400-e29b-41d4-a716-446655440005': {
        'content': a5_content,
        'excerpt': 'The unsettling silence from U.S. intelligence on Epstein\'s surveillance network — and Acosta\'s claim that he was told Epstein "belonged to intelligence."'
    },
    'new-article-001': {
        'content': a6_content,
        'excerpt': 'The documented intersections between Melania Trump\'s world and the Epstein network — including Ghislaine Maxwell\'s attendance at the 2005 Trump wedding.'
    },
    'new-article-002': {
        'content': a7_content,
        'excerpt': 'A careful accounting of the evidence, the expert dispute, and the cascade of institutional failures surrounding Jeffrey Epstein\'s death in federal custody.'
    },
}

for article in articles:
    aid = article['id']
    if aid in updates:
        article['content'] = updates[aid]['content']
        article['excerpt'] = updates[aid]['excerpt']

# Save intermediate
with open('data/articles_partial.json', 'w') as f:
    json.dump(articles, f, indent=2, ensure_ascii=False)

print('Articles 1-7 updated.')
test = json.loads(json.dumps(articles))
print(f'Valid JSON. {len(test)} articles total.')
for a in test:
    wc = len(a['content'].split())
    print(f'  {a["id"][:30]}: {wc} words')
